#+OPTIONS: num:nil toc:nil
#+REVEAL_TRANS: linear
#+REVEAL_THEME: jr0cket
#+Title:  致远者托于骥
#+Author:  Ye Zhaoliang
#+Email: yezhaoliang@ncepu.edu.cn
■徐建中

讲述人：徐建中（1940.3—）

工程热物理专家，中国科学院院士、中国科学院工程热物理研究所研究员，长期从事叶轮机械内部流动的研究。

被讲述人：吴仲华（1917.7—1992.9）

工程热物理学家，中国科学院院士，叶轮机械三元流动通用理论的创始人，工程热物理学科的创立者，中国科学院工程热物理研究所的奠基人。

1963年从中国科技大学毕业以后，我就考上了吴仲华先生的研究生，那时是“文革”以前第一次公开招收研究生。作为第一批研究生，招考非常严格。在中科大的毕业晚会上，吴先生悄悄告诉我：“你被录取了。”一个星期日的下午，我在力学所的303房间见到了吴先生，他对我说了研究生的要求，总的说来就是按照MIT的标准，让我们作好面对困难的准备。

吴先生不仅是国际著名的科学家，更是爱国知识分子的典范。我们要传承和发扬吴先生爱国报国的情怀，严谨求实的科学态度。

怀揣深重的家国情怀

科学没有国界，科学家却有祖国。回忆和吴先生学习的时光，我深深地感到他是一位有着强烈爱国主义精神的科学家。

1950年朝鲜战争爆发后，吴先生旁听了时任外交部苏联东欧司司长的伍修权在联合国的发言，义愤填膺，愤然辞去美国国家航空咨询委员会（NACA）的工作，他和夫人李敏华先生放弃优厚的待遇，一心准备回国。他们利用美国移民局周末休息不办公的机会，以到英国旅游为名，在日内瓦见到周恩来总理，他们根据总理的指示，从东欧经过苏联回到了祖国。

热爱生活，坚守爱情

吴先生在西南联大认识了李敏华先生，他们因音乐而结缘，大学毕业后在昆明结了婚。他们的感情非常好，用李敏华先生的话讲：“我们一辈子都没分开过。”即使在“文化大革命”时期，他们夫妇都被打成“牛鬼蛇神”“资产阶级反动学术权威”，吴先生还坚定地说：“我这一辈子有两件事至今不后悔，一件是回国，一件是和李敏华结婚。”

1943年，年轻的吴先生考取了清华的公费留美生，进入MIT学习。在MIT学习期间，他们的条件比较艰苦，这段期间还生养了两个孩子，一边念书，一边生孩子带孩子，这个负担是可想而知的，特别是对李敏华先生。

读书期间，他们夫妻二人的功课一直很好。1947年吴先生在机械系得到了ScD学位（在美国只有MIT等少数几所学校可以授予ScD，也就是科学博士），1948年李敏华先生获得了PhD，她是MIT航空系的第一位女博士。

李先生为吴先生付出很多，她曾经跟我说：“我后来做的成绩不够大，因为很多时间花在吴仲华身上，他这个人个性很强，不太适应这个社会，所以我总怕他犯错误，花很多时间考虑他的问题，我自己的工作只好放下了。”说到这儿，李先生眼里闪着泪花。

专心科研 创立“叶轮机械三元流动理论”

二战以后不久，航空事业发展非常迅速，NACA在克利夫兰成立了刘易斯实验室，他们夫妇被录用并在那里工作。当时吴先生的老板给了他两个题目，一个叫作气波机械，另一个是航空发动机的叶轮机械。吴先生反复考虑，觉得第一个题目由于有强激波，效率不会高，所以决定做第二个，此后创立了“叶轮机械三元流动理论”。他选题时非常慎重，是经过多方分析、深思熟虑，这也是很重要的一个能力。

吴先生的这个理论对全世界航空发动机的发展起了巨大作用，许多著名飞机用的发动机在设计研制中都用了这一理论；几个大的发动机公司都在这个理论的基础上，形成了自己的设计体系。1945年之前，很多人用机翼理论考虑两个叶片之间的流动，但是吴先生认为用孤立机翼理论做这个题目，叶片之间的相互作用就没有了，所以必须和过去的理论有所不同，因此他首先发挥丰富的想象力：由两个叶片之间的无数流线组成两类不同性质的流面，整个问题就化作流面上参数的确定。他提出了流面偏导数，把空间偏导数和流面偏导数建立起关系，在这样的情况下，他把空间流动的控制方程，通过流面偏导数化到流面上，产生流面上的控制方程。

化到流面上之后，他发现方程中有两个特点：一个是出现流片的厚度，这个厚度就是两个叶片厚度的反映；第二就是出现流面之间的作用力，这个力是叶片两个面压力不同造成的。严格的数学演绎和清晰的物理意义，使整个理论就建立起来了。其核心可以概括为一个中心，两个基本点：中心就是流面偏导数，两个基本点就是流面厚度和流片间的作用力。

这个理论不仅要有想象能力、严谨的数学推导、清晰的物理概念，还要考虑其工程应用时方便。为此，在选择流面时就需要进一步考虑工程的应用性，他提出了著名的S1和S2流面。这个理论充分体现了工程科学的美，堪称一个典范。

他也是大型工程计算的先驱。1946年，世界第一台计算机面世，开发商到NACA去宣传，当时很多人都不用，吴先生却从此勇敢地走上了数字求解的道路。

1952年论文正式发表后，这个理论很快在美国成为主流的设计方法，直到现在依然在应用。1956年NACA出了三大本书，核心就是介绍吴先生的理论。1983年我陪着吴先生参加美国燃气轮机年会，提出超临界翼型的著名学者Hobbs在做poster，当吴先生提问时，他看了一下胸牌，惊讶地说道：“Ar，You Are Famous Wu！”。有人认为斯贝发动机是吴先生设计的，那是不对的，但是它的设计用到了吴先生的理论。

重基础、重实践的人才培养理念

吴先生对学生要求很严格。我们的第一门课叫工程热力学和统计物理。他给一个教学大纲，列了20多本参考书，基本都是国外的。如果有问题可以答一次疑，如果没有就考试。后来我们考试3天，每半天做1个题目。早上8点来，做一道题，12点交卷；下午一点半来，五点半交卷。这种注重培养自学能力的方法，使学生们对问题能深入思考，也使研究能力有了很大的提升。他常对我们说：“我写了这么多论文，没出一点错，除了印刷问题，所以你们以后也要严格要求自己。”

吴先生思考问题的方式、对待工作的严谨态度，让我受益终生。1976年唐山大地震之后，我们住地震棚里面。当时工作比较紧，我们在力学所三楼的大厅坚持工作，大家把计算机带到那儿去做计算。有时候，他会利用一些休息时间和我们谈一些学术上的事情。他讲三元流动理论中有个激波问题，流面上激波是怎么样的，一直没解决。我就在心里记下了这个问题，地震结束后我就去图书馆查文献，自己分析、推导、研究。1978年1月份出国前，我写了一篇东西交给吴先生，当时写在400字一页的稿纸上，用复写纸写了4份。因为这个研究，我成为副研究员。

吴先生对我的影响是多方面的，最重要的是业务上一定要专心和创新，不能跟在别人屁股后面。我们现在一方面要继承吴先生的思想和精神，另外一方面最重要的还是要创新。现在我们有了创新的方法，但我们的旗帜还是吴先生。好不容易有这么一面旗帜，我们不要再丢掉。

（本报见习记者 高雅丽采访整理）
