* 二建
:PROPERTIES:
:ID:       028fb716-d540-4ae1-b1fa-d31ffb403996
:END:

** 能建
:PROPERTIES:
:ID:       53fb21ad-ff3c-4ddd-9fa5-5468f8d25226
:END:

*** 董事长、执行董事
:PROPERTIES:
:ID:       549ed3ac-2a91-4176-8423-3a68170d7b25
:END:

汪健平
**** 独立非执行董事
:PROPERTIES:
:ID:       cdd600fd-8d29-472a-bc6a-77750e911e88
:END:
**** 非执行董事
:PROPERTIES:
:ID:       c0681d79-4165-4615-a5f0-f35f4596bb0f
:END:

马传景  丁原臣   王斌  郑起宇  张钰明
**** 副总经理、执行董事
:PROPERTIES:
:ID:       361d27e7-8357-41fa-9c1c-d40f56b68819
:END:

张羡崇
**** 副董事长、总经理、执行董事
:PROPERTIES:
:ID:       cc4e0726-c55b-4f08-9e62-a0bca02c2c68
:END:

丁焰章
** 电建
:PROPERTIES:
:ID:       af5e026a-d101-4997-b158-5a3bf196e17e
:END:
*** 党委书记、董事长
:PROPERTIES:
:ID:       229e6d17-eebb-4747-bafb-6748a0c59c6e
:END:

晏志勇
**** 党委常委
:PROPERTIES:
:ID:       2a5a30b1-42b8-4861-8cf2-5640bde0c175
:END:

王民浩 姚强   李跃平   孙璀   李燕明
**** 党委常委、纪委书记
:PROPERTIES:
:ID:       7721e515-eca7-43b7-bcdd-5d5c62388bdc
:END:

符岳岩

**** 党委副书记
:PROPERTIES:
:ID:       21ad2c4f-fb0b-4744-98e0-ce8d801598bf
:END:

王斌
**** 党委副书记、总经理、董事
:PROPERTIES:
:ID:       95d17df3-581a-4321-aa87-a3fccee1ca1b
:END:

孙洪水
* 三大电气集团
:PROPERTIES:
:ID:       de468881-4d4d-4507-96ef-262474709e21
:END:

** 西电(中国西电集团有限公司)
:PROPERTIES:
:ID:       d26659cc-6d48-41c3-a692-c1de409ac410
:END:

*** 董事长、党委书记
:PROPERTIES:
:ID:       2b39a127-d2d7-4ce1-81d1-4651450ef0c2
:END:

张雅林
**** 党委常委
:PROPERTIES:
:ID:       5efb12b6-fa7c-44db-be93-8544814c6794
:END:

郝连明利  汪健忠
**** 董事、党委副书记
:PROPERTIES:
:ID:       3b34cc72-f6c8-48c4-88e0-6af18a367b73
:END:

张明才
**** 党委副书记、纪委书记
:PROPERTIES:
:ID:       17ac75cb-c090-46d8-8793-22ff39a968aa
:END:

牛新安
**** 董事、党委常委
:PROPERTIES:
:ID:       28ceba70-d2aa-45bb-b463-924a9af947b3
:END:

裴振江
** 东电(中国东方电气集团有限公司)
:PROPERTIES:
:ID:       26e6a0e2-1915-4c27-a975-cc02232487f4
:END:
*** 党组书记、董事长
:PROPERTIES:
:ID:       eb8cf724-23d4-4a2f-b675-60c48a55801c
:END:

邹磊

2018年6月29日，东方电气宣布，于2018年6月29日举行的董事会第一次会议上，邹磊被选举为董事会董事长，任期三年，并于同日起生效。
**** 党组副书记、董事、总经理
:PROPERTIES:
:ID:       822ff1d7-4d43-47e1-ad3d-824023f114e6
:END:

张晓仓

***** 党组成员、总会计师
:PROPERTIES:
:ID:       3f47075b-946e-4e21-83f8-41136aaf713a
:END:

白勇
***** 党组成员、副总经理
:PROPERTIES:
:ID:       09fa25d9-ba2e-40bb-8265-61178659da8f
:END:

徐鹏  张继烈
***** 党组成员、党组纪检组组长
:PROPERTIES:
:ID:       421e3b5f-c398-48b3-a289-a27bf2ec0c9b
:END:

胡乃民
***** 党组副书记、副总经理、总部直属党委书记
:PROPERTIES:
:ID:       32176ff0-fdf9-476e-bb5c-b7d17de92f03
:END:

黄伟
** 哈电(哈尔滨电气集团公司)
:PROPERTIES:
:ID:       96355895-3797-4e93-b2fc-921be65f5487
:END:
*** 党委书记、董事长
:PROPERTIES:
:ID:       a63184c6-48d0-4621-87d9-a889106597e3
:END:

斯泽夫
**** 总经理助理、企管总监
:PROPERTIES:
:ID:       d5fea995-c2c8-4f7b-85d9-97f1fa18089a
:END:

曲哲
**** 总经理助理、营销总监
:PROPERTIES:
:ID:       b80c7614-068b-49f9-9194-ee18df6a378c
:END:

张海权
**** 总经济师
:PROPERTIES:
:ID:       d0bb4c8c-772e-410e-b8d3-dd7f770450ea
:END:

王德兴
**** 总会计师
:PROPERTIES:
:ID:       5c4fd9a8-206c-49f0-931c-aebe3aab20f7
:END:

刘智全
**** 副总经理
:PROPERTIES:
:ID:       bd1096d6-1211-4345-af0b-2b76d86c9233
:END:

宋世麒
**** 党委常委、副总经理
:PROPERTIES:
:ID:       68ed92e2-3d99-4e18-b2ea-e4295bf99a90
:END:

张英健
**** 党委副书记
:PROPERTIES:
:ID:       80165841-21f0-4508-9998-2665c7814438
:END:

孙智勇
**** 党委副书记、董事、总经理
:PROPERTIES:
:ID:       2b3f2ed7-ad76-4fab-95bd-a72db6f5c6c6
:END:

吴伟章
* 四小
:PROPERTIES:
:ID:       b1e17174-ea37-490c-810f-28f3778ebb8d
:END:

** 华润电力
:PROPERTIES:
:ID:       4b644056-d415-43b4-8ffd-d625c48f4b2d
:END:

*** 董事、总裁
:PROPERTIES:
:ID:       c03af0cc-f447-405f-87b8-83c595f64f7d
:END:

胡敏

董事会和管理层的人不一样，我这普遍放的是“管理团队”的。华润电力“董事会”的第一位的确是李汝革。
**** 助理总裁兼战略发展部总经理
:PROPERTIES:
:ID:       c74d8424-7da7-480d-ad04-e38e2db663c0
:END:

许红波
**** 助理总裁监总法律顾问
:PROPERTIES:
:ID:       602c520a-3e82-4097-b575-1dd28193b0d5
:END:

张刚
**** 助理总裁兼信息管理总监
:PROPERTIES:
:ID:       f4794b9e-3433-45c4-854d-63d4a3867291
:END:

安兴
**** 副总裁兼审计总监
:PROPERTIES:
:ID:       cba1605b-d3fd-46db-97dc-ed49404383c9
:END:

王国强
**** 副总裁
:PROPERTIES:
:ID:       6015a4e6-b02c-49ca-932f-95e3dd62ba49
:END:

丁琦  赵后昌   丁远奎   王林  后永杰
**** 高级副总裁、财务总监
:PROPERTIES:
:ID:       284a9192-cba4-4fb6-8e88-25cbe9e10721
:END:

朱国林
**** 高级副总裁
:PROPERTIES:
:ID:       db858980-21c0-41f4-805f-c362ac076664
:END:

姜利辉    
**** 执行董事、首席财富官
:PROPERTIES:
:ID:       787a4ec0-2f98-4bf4-82d1-05d8817bc02f
:END:

王小彬
**** 副主席、执行董事、高级副总裁
:PROPERTIES:
:ID:       d0e5fc9c-e098-4afb-8ced-3bd1eb065c73
:END:

葛长新
** 三峡
:PROPERTIES:
:ID:       ef2f54dc-df67-4f79-883d-0dbf16fbe060
:END:
*** 党组书记、董事长、中国人名政治协商会议第十三届委员会常务委员
:PROPERTIES:
:ID:       f66c5ca8-f5c7-4a54-98f3-e9df24d9892e
:END:

卢纯

三峡集团董事长、党组书记卢纯1955年5月生，现已63岁。

这些央企“一把手”或许即将面临人事变动。
**** 董事、总经理、党组副书记
:PROPERTIES:
:ID:       1372e9ec-1e16-4549-b35b-633d08299639
:END:

王琳
***** 党组成员、纪检组组长
:PROPERTIES:
:ID:       220cad41-44a9-4703-b5ed-5254a78f9991
:END:

龙飞
***** 党组成员、总会计师
:PROPERTIES:
:ID:       05b65628-b6ea-4b4e-ba24-94e4fa521b10
:END:

杨亚

***** 党组成员、副总经理
:PROPERTIES:
:ID:       234ca2b3-b204-4ac7-8911-e65afab3fa2d
:END:
***** 党组副书记、副总经理
:PROPERTIES:
:ID:       2802bb43-708b-4aa7-adc0-cb1425898fc8
:END:


林初学, 王良友， 范夏夏，张定明

2018年7月3日，长江电力发布公告称，董事会于近日收到董事、总经理张定明的书面辞职报告。
因工作原因，张定明辞去公司董事、总经理、战略与环境委员会委员职务。

2018年7月5日，长江电力发布第四届董事会第二十六次会议决议公告，提名马振波先生、陈国庆先生、赵强先生为公司第四届董事会非独立董事候选人，
任期自股东大会审议通过之日起，至第四届董事会任期届满时结束;聘任陈国庆先生担任公司总经理
** 中广核
:PROPERTIES:
:ID:       cda0c3e1-7927-40bf-85a2-eed7a65ea147
:END:
*** 党委书记、董事长
:PROPERTIES:
:ID:       d29d5678-9fe2-49f3-a472-764dd1a6142f
:END:

贺禹
**** 党委副书记、总经理
:PROPERTIES:
:ID:       df93bc3e-2def-4fa4-a231-7ec138fe16d2
:END:

张善明

7月11日，中广核技发布公告，张剑锋因个人原因向公司董事会辞去公司董事、董事长及董事会下属专门委员会相关职务。
***** 副总裁
:PROPERTIES:
:ID:       086c80e7-8f17-41af-8191-1624c32acc5f
:END:

陈映坚  蒋达进
5月29日，中广核电力发布公告，陈映坚和蒋达进已获委任为公司副总裁，自2018年5月29日起生效，任期均为3年。
***** 党委常委、总会计师
:PROPERTIES:
:ID:       e460c7b4-40da-4885-8358-9b4bb8b0ae2a
:END:

吴俊峰
***** 党委常委、纪委书记
:PROPERTIES:
:ID:       80b08431-0aa5-42ae-a627-d1fa369055cf
:END:

李友荣
***** 党委常委、中广核电力总裁
:PROPERTIES:
:ID:       aebde4bf-9ed4-403c-a02c-9a5e7493977a
:END:

高立刚
***** 党委常委、副总经理
:PROPERTIES:
:ID:       101a333a-f991-4b69-9444-d2582ca93ad7
:END:

谭建生  施兵   束国刚  庞松涛  
* 国家能源投资集团
:PROPERTIES:
:ID:       9e1bafc6-5406-4b80-900c-0e18ebfdae8d
:BRAIN_CHILDREN: 58d959ff-9e79-4f9c-a22b-77fc6e6c8a5f
:END:
** 党组书记、董事长
:PROPERTIES:
:ID:       a0c7c3f3-a475-45e9-b54d-84f10ef95c58
:END:

乔保平

国家能源集团党组书记、董事长乔保平1955年12月生，现已63岁

7月6日，龙源电力发布第一次临时股东大会的投票结果及监事变更信息，于本公告日期，
本公司的非执行董事为乔保平先生、刘金焕先生、栾宝兴先生和杨向斌先生;执行董事为李恩仪先生和黄群先生;
及独立非执行董事为张颂义先生、孟焰先生和韩德昌先生。
*** 纪检组组长、党组成员
:PROPERTIES:
:ID:       f7ce463d-089b-41a4-a6bc-baedd2d33abd
:END:

卞宝驰
*** 总会计师、党组成员
:PROPERTIES:
:ID:       eee89d5f-08e8-4d66-9c5d-ef8d96095cc5
:END:

陈斌
*** 副总经理、党组成员
:PROPERTIES:
:ID:       f9732d59-544e-4419-9e07-7f3092d8c6de
:END:

高嵩  米树华  王金力  王树民 李东
*** 党组副书记
:PROPERTIES:
:ID:       ec86cc9d-7e87-41bc-8132-4650bb5d2c01
:END:

韩建国、 张国厚

国家能源集团党组副书记韩建国，已于2018年5月15日向中国神华董事会递交辞呈，因已届退休年龄辞
去中国神华执行董事职务，其董事会提名委员会委员、战略委员会委员职务也同时终止。韩建国1958年生，今年60岁。

*** 董事、总经理、党组副书记
:PROPERTIES:
:ID:       a7eff539-6a32-4ab0-bbf6-1354cadb4f61
:END:

凌文
* 五大
:PROPERTIES:
:ID:       acb19baf-b9e8-4466-aa18-e7665c47eadb
:BRAIN_PARENTS:
:END:
** 神华
:PROPERTIES:
:ID:       58d959ff-9e79-4f9c-a22b-77fc6e6c8a5f
:BRAIN_PARENTS: 9e1bafc6-5406-4b80-900c-0e18ebfdae8d
:END:
*** 党委书记、董事长
:PROPERTIES:
:ID:       674c542a-f508-4fc3-a89a-4735fef7a6d7
:END:

张玉卓

2018年5月31日，因已届退休年龄，中国神华副总裁张子飞向董事会辞任副总裁一职，即日生效。
**** 副总经理、党组成员
:PROPERTIES:
:ID:       cf82a629-1f2f-4a6b-b16e-25e4b0366a28
:END:

王树民
**** 总经理
:PROPERTIES:
:ID:       e4efd636-433b-4e4f-8b67-0f7f41227f77
:END:
凌文
*** 国华电力
:PROPERTIES:
:ID:       35a0750d-4925-4ea1-af88-6db56a1f00ae
:END:
**** 党委书记、董事长
:PROPERTIES:
:ID:       02684a06-e267-44e7-a50a-730cb029ab63
:END:

肖创英
***** 纪委书记
:PROPERTIES:
:ID:       d1b8b5f8-862d-4317-b423-c7a20cddce60
:END:

邢仓
***** 副总经理
:PROPERTIES:
:ID:       d093fbee-97ab-4044-a658-0ee71e15c2ee
:END:

耿育
***** 总工程师
:PROPERTIES:
:ID:       59bb8c9b-3abe-4793-a24e-9e2132ab5d8c
:END:

陈寅彪
***** 副总经理、财务总监
:PROPERTIES:
:ID:       54a58a91-3407-4b4b-9d0a-ae44e7d06b95
:END:

沈玉章
***** 党委副书记、总经理
:PROPERTIES:
:ID:       13545036-236f-46c8-b817-393dfabb0a6f
:END:

李巍
***** 党委副书记、副董事长
:PROPERTIES:
:ID:       cdd4e20c-0377-45f8-aebb-336f2a367d71
:END:

夏利
** 国电投
:PROPERTIES:
:ID:       098f33f0-2e8e-41ba-a810-97f3c8f34c40
:END:
*** 董事长、党组书记
:PROPERTIES:
:ID:       e9e59339-8089-46ae-a3c7-0984948dc701
:END:

钱智明

**** 党组副书记、总经理、董事
:PROPERTIES:
:ID:       5c737524-454c-4b84-a140-bd501f1dbce4
:END:

孟振平
***** 党组成员、纪检组组长
:PROPERTIES:
:ID:       e988707a-1a66-4f27-b0b8-f60938175bd4
:END:

谢俊

2018年5月31日下午，国家电投召开领导班子扩大会议，通报了中组部关于谢俊同志任国家电力
投资集团有限公司党组纪检组组长、党组成员;免去邓文奎同志的国家电力投资集团有限公司党组纪检组组长、党组成员职务的决定。
***** 党组成员、总会计师
:PROPERTIES:
:ID:       2b023542-97e4-4940-a327-008eaeeb0198
:END:

王益华
***** 党组成员、副总经理
:PROPERTIES:
:ID:       b73442e7-5ee3-4334-8dc0-91a1fa081220
:END:

夏钟  魏锁  时家林
***** 党组副书记、董事
:PROPERTIES:
:ID:       84cb0d17-b430-47cb-8876-45c0ae2dd1eb
:END:

江毅
*** 中电投
:PROPERTIES:
:ID:       e23e47f9-3352-439c-8e0a-1807fa3cde8d
:END:
**** 国投电力
:PROPERTIES:
:ID:       1303dba5-a39b-428e-a355-f2201dda6397
:END:
***** 党委书记、总经理
:PROPERTIES:
:ID:       0ef02a17-c278-4bdd-8499-60cb02f85fd7
:END:

朱基伟
****** 总经理秘书
:PROPERTIES:
:ID:       f6a91230-7ffd-4bd4-8b5e-ba1623c5e8c2
:END:

杨林
****** 总经理助理
:PROPERTIES:
:ID:       4ae18f22-77e6-4593-9fb6-dd5100e49f25
:END:

江华
****** 副总经理
:PROPERTIES:
:ID:       a8d4b7c9-e805-4b00-a020-3b6948c3629b
:END:

曲立新  赵风波
**** 中核
:PROPERTIES:
:ID:       79450a58-f41d-4f09-915e-14726ee4a9f7
:END:
***** 党组书记、董事长
:PROPERTIES:
:ID:       c1889cb4-a3e7-4b0a-b71f-403c8753a0cf
:END:

王寿君
****** 中国核电董事长、党委书记
:PROPERTIES:
:ID:       ec9402cc-2e83-41f9-a375-78c68e007c0d
:END:

陈桦
****** 总工程师
:PROPERTIES:
:ID:       7097f2ed-8a93-4c11-be24-e74149285f80
:END:

雷增光
****** 董事会秘书
:PROPERTIES:
:ID:       6009d436-da5f-41e5-ad4f-b66755244ac3
:END:

潘建明
****** 总经理助理
:PROPERTIES:
:ID:       44adaf5b-6b54-4c23-a55d-6a960fce89e4
:END:

李晓明
****** 总经济师
:PROPERTIES:
:ID:       affe7872-3b70-4c62-8dd8-d833d4aa68bb
:END:

黄敏刚
****** 党组成员、纪检组组长
:PROPERTIES:
:ID:       69f5fb72-5f85-45cb-abf7-bb82090d0e96
:END:

王杰之
****** 党组成员、副总经理
:PROPERTIES:
:ID:       0be4cecb-4a67-4297-947f-02f515d30ff4
:END:

杨长利、 俞培根、曹述栋、和自兴
****** 党组副书记、总经理
:PROPERTIES:
:ID:       dcea3850-7b95-4a09-a623-9b3493fb517e
:END:

余剑锋
*** 国电
:PROPERTIES:
:ID:       55049e2a-fd23-49c6-9acd-a3a98656f82c
:END:
** 大唐
:PROPERTIES:
:ID:       f0ef4795-a478-4dd5-b5a3-8beb3702bf9a
:END:
*** 董事长、党组书记
:PROPERTIES:
:ID:       11d6aa9e-6af1-4a90-a73b-46a1276d389e
:END:

陈进行
大唐集团董事长、党组书记陈进行1955年6月生，现已63岁
**** 董事、总经理、党组副书记
:PROPERTIES:
:ID:       ef6fdaf9-fc4c-408a-bac3-d296d23ef6cd
:END:

陈飞虎
***** 副总经理
:PROPERTIES:
:ID:       3d23d216-5c67-422b-8860-d2c3328cd388
:END:

金耀华

2018年6月6日，大唐发电发布公告，董事会会议同意洪绍斌、孟繁逵及段忠民自2018年6月6日起不再担任公司副总经理。

6月26日，大唐新能源公布了最新董事名单与其角色和职能。非执行董事为陈飞虎(董事长)、刘光明、李 奕、刘宝君;
执行董事为周克文(副董事长)、孟令宾;独立非执行董事为刘朝安、卢敏霖、余顺坤。
***** 党组成员、总会计师
:PROPERTIES:
:ID:       c4c129b3-8776-4e48-91ed-4ceee059b4f1
:END:

刘传东
***** 党组成员、纪检组长
:PROPERTIES:
:ID:       817ca460-a41d-4cbc-8451-d9a078cc7fc7
:END:

熊皓
***** 党组成员、副总经理
:PROPERTIES:
:ID:       c6465f17-3e5f-466d-acfb-2be44461c4eb
:END:

胡绳木  王森  吴秀章
***** 党组副书记、副总经理
:PROPERTIES:
:ID:       45b09fa3-e389-431f-b025-a04b01757ebe
:END:

邹嘉华
** 华电
:PROPERTIES:
:ID:       5bec406d-f405-4939-9b17-421bf8a50549
:END:
*** 党组书记、董事长
:PROPERTIES:
:ID:       0bd41286-e545-4fc6-90e9-877a864938d7
:END:

赵建国
**** 董事、总经理、党组副书记
:PROPERTIES:
:ID:       15868eac-a5d8-4b96-8951-2e285c2f45d6
:END:

温枢刚
***** 党组成员、副总经理
:PROPERTIES:
:ID:       c2ef002b-4fe3-437d-bbf6-221e8fdac71e
:END:

陈建华  杨清廷  王宏志

2018年6月29日，华电福新发布公告，公告称由于个人工作调动原因，李一男先生辞任非执行董事及审核与风险管理委员会成员。
***** 党组成员、纪检组长
:PROPERTIES:
:ID:       dacf20aa-8aa9-4919-b5a7-fccd4045396d
:END:

张本平
***** 党组成员、总会计师
:PROPERTIES:
:ID:       f0aa7808-5691-40f9-b4b8-5cd4789554b0
:END:

邵国勇
***** 党组副书记、副总经理
:PROPERTIES:
:ID:       7eece549-6fab-4dd9-beac-a679a91f2d17
:END:

仁书辉

** 华能
:PROPERTIES:
:ID:       f626f05b-9600-4cbd-9fca-510116322ade
:END:
:RESOURCES:
:END:


*** 董事长、党组书记
:PROPERTIES:
:ID:       64b52484-6e2b-400d-bf14-f7eb22bad12d
:END:

曹培玺

华能集团董事长、党组书记曹培玺1955年8月生，现已63岁；
**** 党组成员、纪检组组长
:PROPERTIES:
:ID:       8b6dd6ed-0169-469f-8c56-0d9d818b1b8c
:END:

赵建明
**** 副总经理、党组成员
:PROPERTIES:
:ID:       3aadce0b-8173-4492-bb40-b915e18b1c32
:END:


樊启祥  王敏  叶向东  王文宗
**** 党组副书记、副总经理
:PROPERTIES:
:ID:       fb15f321-662a-48d5-9a7e-829572ec21c8
:END:

邓建玲

已不在华能集团官网领导人之列的原华能集团董事、总经理、党组副书记黄永达1957年11月生，现已61岁

*** 2. 子单位
:PROPERTIES:
:ID:       18d0c1aa-2709-40e1-9c2e-2323a80f5185
:END:

| 单位名称                               | 笔试日期    | 面试日期       |
|----------------------------------------+-------------+----------------|
| 中国华能集团有限公司技术经济研究院     | 2019/1/10   |                |
| 中国华能集团有限公司信息中心           |             |                |
| 华能国际电力开发公司                   |             |                |
| 华能国际电力股份有限公司               | 2019/1/16   |                |
| 华能新能源股份有限公司                 | 2019/1/13   |                |
| 华能核电开发有限公司                   | 2019/1/16   |   2019-01-23　 |
| 华能能源交通产业控股有限公司           | 2019/1/18   |                |
| 北京华源瑞成贸易有限责任公司           | 2019/1/14   | 2019/1/18      |
| 华能煤业有限公司                       | 2019/1/15   | 2019/1/16      |
| 中国华能集团燃料有限公司               |             |                |
| 华能资本服务有限公司                   | 2019/1/12   |                |
| 中国华能财务有限责任公司               |  2019-01-14 |  2019-01-18    |
| 中国华能集团清洁能源技术研究院有限公司 |  2019-01-12 |                |
| 华能置业有限公司                       | 2019/1/15   | 2019/1/18      |
| 新升物业管理有限公司                   | 2019/1/15   | 2019/1/18      |
| 华能海外企业管理有限公司               |             |                |
| 华能北京热电有限责任公司               |             |                |
|----------------------------------------+-------------+----------------|
| 18                                     |             |                |

*** DONE [#B] 参加华能笔试 <2019-01-10 周四 16:09>                    :@NCEPU:
CLOSED: [2019-01-12 周六 21:13] DEADLINE: <2019-01-12 周六>
                    :PROPERTIES:
                    :CREATED: [2019-01-10 周四 16:09]
                    :Effort: 1:00
                    :END:
                    :LOGBOOK:
                    - State "DONE"       from "TODO"          T:[2019-01-12 周六 21:13]
                    CLOCK: [2019-01-10 周四 16:10]--[2019-01-10 周四 16:16] =>  0:06
                    :END:

西单站J2出口 民生银行西侧（1-12 下午2点开始，半小时提前入场)
招聘单位中国华能集团清洁能源技术研究院有限公司本部(机械工程)
坐地铁过去吧，不然限行!

**** 题目
1英译汉汉译英(知之为知之，不知为不知，是知也, 给了一段巴黎协议的中文，要翻译 )
2数理题（积分，极限，微分方程，工程制图三视图，热力学三大定律，化学反应）
3文史题（19大，表达心怀天下的古诗，孟子，孔子。陆游，杜甫）
4论述题（风电，火电等任选，论述技术原理，发展现状和趋势）
5问答题（英语回答华能是什么，为什去清能源，中文回答科研人员该具备什么素质，一项任务你觉得该怎么完成，如果领导觉得你的任务不可能完成了，你要怎么做？）
**** 求导

**** 古诗词
***** 习语
****** 学而不思则罔，思而不学则殆

　　——习近平在中央党校建校80周年庆祝大会暨2013年春季学期开学典礼上的讲话（20
13年3月1日）
典出：《论语·为政》

　　原文：同引用

　　释义：只学习、不思考，就会迷惘；只思考、不学习，思考也会陷入困境。

　　注重学习和思考之间的关系。学习包括从书本上学，也包括从实践中学。“思”可以理
解为问题意识，只有带着问题学，学习才有方向。“言必称希腊”或者认为中国应该照搬
西方制度的观点，就是典型的“学而不思”；同样，要解决问题，也必须重视学习，通过归
纳总结过去好坏两方面的做法和借鉴他人的经验，才有可能真正找到解决问题的钥匙。

****** 　　知之者不如好之者，好之者不如乐之者

　　——习近平在中央党校建校80周年庆祝大会暨2013年春季学期开学典礼上的讲话（20
13年3月1日）

　　典出：《论语·雍也》

　　原文：同引用

　　释义：懂得一种知识的人不如爱好它的人，爱好它的人不如能从中得到乐趣的人。宋
代朱熹《四书集注》说：“知之者，知有此道也。好之者，好而未得也。乐之者，有所得而
乐之也。”

　　兴趣是最好的老师。在孔子看来，学习的最高境界，是能够将学习作为一种乐趣。他
自己在齐国学习韶乐，三个月不知肉味，乐在其中。今天我们常常赞赏一些学有所成的人
物，如何艰苦地进行创造，其实他们从学习和创造中一定也享受到了巨大的快乐，正是这
种快乐，不仅引领着他们的工作，也往往让他们忽略了物质条件的不足，最终让他们取得
别人难以企及的成功。

****** 　　三人行，必有我师焉

　　——习近平《之江新语·要善于学典型》

　　典出：《论语·述而》

　　原文：三人行，必有我师焉，择其善者而从之，其不善者而改之。

　　释义：与众人相处，其中必定有可以做我老师的人。

　　人最忌自以为是。从知识的角度看，人不可能穷尽世间所有，个人所掌握的，只是浩
淼知识海洋中的一小部分。从经验的角度看，每个人都有不同的生活经历，由经历生成的
知识必然各有不同。从时间的角度看，人的生命长度有限，每个人都只能是历史中一个渺
小的点，“吾生也有涯，而知也无涯”，自以为是，目空一切，说到底还是“无知”。所以，
聪明人应该时刻保持谦虚的心态，多看到他人的长处，善于从他人得失经历中得到镜鉴。

****** 　　博学之，审问之，慎思之，明辨之，笃行之

　　——习近平在中央党校建校80周年庆祝大会暨2013年春季学期开学典礼上的讲话（20
13年3月1日）

　　典出：《礼记·中庸》

　　原文：“博学之，审问之，慎思之，明辨之，笃行之。有弗学，学之弗能，弗措也；
有弗问，问之弗知，弗措也；有弗思，思之弗得，弗措也；有弗辨，辨之弗明，弗措也；
有弗行，行之弗笃，弗措也。人一能之，己百之，人十能之，己千之。果能此道矣，虽愚
必明，虽柔必强。”

　　释义：博学，学习要广泛涉猎；审问，有针对性地提问请教；慎思，学会周全地思考
；明辨，形成清晰的判断力；笃行，用学习得来的知识和思想指导实践。

　　古人谈学习的五个方面，不管是学习书本知识也好，学习某种技能也好，都得经过反
复训练才能完成。“有弗学”的意思是要么不学，学就要学会；如果学了还不会，“弗措也
”，也就是说绝不放弃。这段话，不是对天才，而是对一般人说的，聪明人一下就学会，
你就学一百下，聪明人十次能学会的，你就学一千次。只要有这种韧劲，开始哪怕迟钝一
点，会变得聪明的；开始柔弱的人，也会变得强壮有力。

****** 　　不登高山，不知天之高也；不临深溪，不知地之厚也。

　　——习近平在全国组织工作会议上的讲话（2013年6月28日）

　　典出：《荀子·劝学》

　　原文：君子曰：学不可以已。青，取之于蓝而青于蓝；冰，水为之而寒于水。木直中
绳，輮以为轮，其曲中规，虽有槁暴，不复挺者，輮使之然也。故木受绳则直，金就砺则
利，君子博学而日参省乎己，则知明而行无过矣。故不登高山，不知天之高也；不临深溪
，不知地之厚也；不闻先王之遗言，不知学问之大也。

　　释义：不登上高山，不知道天有多高；不走近峡谷，不知道地有多厚。这段话的意思
反过来说还有一句常用的谚语：不知天高地厚。

　　人类知识是一个漫长的积累过程。荀子在《劝学》开篇就说，学无止境。他通过形象的
比喻，告诫人们学习应该抱有谦虚的态度。只有真正了解前人丰厚的知识成果，才能知道
自己的不足，才能在前人的基础上进行创造。对此，大科学家牛顿也有一段名言，“如果
说我比别人看得更远一些，是因为我站在了巨人的肩膀上。”

****** 　　学者非必为仕，而仕者必为学

　　——习近平在中央党校建校80周年庆祝大会暨2013年春季学期开学典礼上的讲话（20
13年3月1日）

　　典出：《荀子·大略》

　　原文：君子进则能益上之誉而损下之忧。不能而居之，诬也；无能而厚受之，窃也。学者非必为仕，而仕者必如学。

　　释义：读书人不一定都要做官，但为官者必须坚持学习以不负平生所学。

　　荀子在这段话里提到了三种人，“君子”、“学者”和“仕者”。古人讲“学而优则仕”，学者是很可能转化为仕者的，但是无论学者还是仕者，要达到君子的境界，并不容易。荀子认为，君子出来做官，应该让君王的声誉更好，同时也减少治下百姓的民生愁苦。如果做不到这点，还占据官位，那就是欺骗；没有做官的能力还享受丰厚的俸禄，无异于盗窃。因此，官员应该提高学习能力，为国家、百姓做实事，真正做到“不负所学”。

****** 　　非学无以广才，非志无以成学

　　——习近平在北京大学师生座谈会上的讲话（2014年5月4日）

　　典出：三国·诸葛亮《诫子书》

　　原文：夫君子之行，静以修身，俭以养德。非淡泊无以明志，非宁静无以致远。夫学须静也，才须学也，非学无以广才，非志无以成学。

　　释义：不学习就难以增长才干，不立志就难以学有所成。

　　诸葛亮告诫自己孩子的这封信里，留下了许多名句。纵观全篇，可见他着重强调“静”字。只有内心宁静，才能养成定力，有了定力，才能明确志向，安心学习，增长才干。在现代社会，物质极大丰富的同时，也在不其然间助长了享乐主义和奢靡之风，这就更需要淡泊名利，涵养心性。以浮躁的心态来为人处世，终将会一事无成。

****** 　　学所以益才也，砺所以致刃也

　　——习近平《之江新语·要善于学典型》

　　典出：汉·刘向《说苑·建本》

　　原文：子思曰：学所以益才也，砺所以致刃也，吾尝幽处而深思，不若学之速；吾尝跂而望，不若登高之博见。故顺风而呼，声不加疾而闻者众；登丘而招，臂不加长而见者远。故鱼乘于水，鸟乘于风，草木乘于时。

　　释义：要想增加才干，就要学习；要使刀刃锋利，就得勤加磨砺。

　　《说苑》的这个小故事里，子思讲了一个道理：要想增长本领，必须找对方法，方法找对，事半功倍。与其“宅”在家里空想（解决办法），不如向人学习来得迅速；与其惦起脚来张望，不如登上高处看得广远。要解决“本领不够”的问题，有很多办法，其中，向典型学习就是一种好办法，学习典型也是增长本领的“磨刀石”。

****** 　耳闻之不如目见之，目见之不如足践之

　　——习近平在全国组织工作会议上的讲话（2013年6月28日）

　　典出：汉·刘向《说苑·政理》

　　原文：夫耳闻之，不如目见之；目见之，不如足践之。

　　释义：从别人那里听来的事情，没有亲眼所见的可靠；亲眼所见，又不如亲自尝试去做。

　　无论为学还是为政，实践都是非常重要的。只有在实际的学习和工作中探索，才能发现真问题，也才能找到解决问题的办法。做官为政更是如此，仅仅坐在办公室里听汇报、看文件，是不可靠的，拍脑袋做决定，更是会贻误大事的。为政者要真正了解社情民意，必须深入到基层，亲自到社区村庄和群众交流交心，只有深入开展调查研究，才能做出切实可行的决策方案。

****** 　　学而不化，非学也

　　——习近平在全国宣传思想工作会议上的讲话（2013年8月19日）

　　典出：宋·杨万里《庸言》

　　原文：同引用

　　释义：学习却不能够融会贯通，不是有意义的学习。

　　对一般人来说，学习的目的是要致用，特别对领导干部来说，学习是为了提高认识水平，增强治理能力。因此，学习的过程本身就是一个融会贯通的过程，学习却不懂得灵活运用，就容易掉进本本主义的坑里。中国传统、别国经验等等，都可以成为我们学习借鉴的资源，但是最重要的还是根据我们自己的现实国情，加以消化、取舍、扬弃、运用，否则，难免会犯“食古不化”、“师洋不化”的毛病。

知识不把他用起来就是死的，想要用起来就得多思考，多琢磨，胸中脱去尘浊，自然丘壑
内赢,立成鄄鄂

立成鄄鄂意思就是很快就能完成一幅佳作，实际上鄄就是指山东鄄城，位于菏泽地区，以前是一处风景极佳之地，鄂就是指鄂州，风景自不必说了。

****** 　　读万卷书，行万里路

　　——习近平在俄罗斯“中国旅游年”开幕式上的致辞（2013年3月22日）

　　典出：明·董其昌《画禅室随笔》

　　原文：“画家六法，一气韵生动。气韵不可学，此生而知之，自有天授，然亦有学得处。读万卷书，行万里路，胸中脱去尘浊，自然丘壑内营，立成鄄鄂。”

　　释义：多阅读（以增长才学），多游历（以增加见识）。

　　董其昌谈画，认为只有多读书、多游历，才能胸中有丘壑，作品成气韵。一是要多读书，诗圣杜甫说，“读书破万卷，下笔如有神”；二是要多游历，现代交通发达，旅游业繁荣昌盛，不用像古代徐霞客那样苦行，但要想如徐霞客那样在游历中获得生命的宽度，却需要今人付出更多的思考(路再走，思考也在继续)。

****** 学习、才能、见识

　　学如弓弩，才如箭镞

　　——习近平在同各界优秀青年代表座谈时的讲话（2013年5月4日）

　　典出：清·袁枚《续诗品·尚识》

　　原文：学如弓弩，才如箭镞（zu)，识以领之，方能中鹄

　　释义：学习就像拉开的弓弩，才能就像箭头，还要用见识来引导，射出去的箭才能击中鹄的（达成目标）。

　　袁枚在短短16字中，用一个比喻讲了学习、才能和见识的关系。学习是基础，基础打得越牢，用的时候才能劲道十足，否则就会“学到用时方知少”；才能是显现出来的能力，磨砺出锋利的箭头（弓、弩；箭、镞），才能“李广射虎，中石没镞”；见识就是射箭人高明的视野和目力，如此方能射中天上飞的鸿鹄。因此，我们在平常的学习，也需要锤炼出厚实的见识，才能更好地利用自己的才能完成工作目标。

****** 治学三境界


　　治学三境界：“昨夜西风凋碧树，独上高楼，望尽天涯路”；“衣带渐宽终不悔，为伊消得人憔悴”；“众里寻他千百度，蓦然回首，那人却在灯火阑珊处”。

　　——习近平在中央党校2009年春季学期第二批进修班暨专题研讨班开学典礼上的讲话（2009年5月13日）

　　典出：清·王国维《人间词话》

　　原文：同引用

　　释义：这是国学大师王国维论治学的三种境界。习近平认为，领导干部读书学习也应该有这三种境界：首先，要有“望尽天涯路”那样志存高远的追求，有耐得住“昨夜西风凋碧树”的清冷和“独上高楼”的寂寞，静下心来通读苦读；其次，要勤奋努力，刻苦钻研，舍得付出，百折不挠，下真功夫、苦功夫、细功夫，即使是“衣带渐宽”也“终不悔”，“人憔悴”也心甘情愿；再次，要坚持独立思考，学用结合，学有所悟，用有所得，要在学习和实践中“众里寻他千百度”，最终“蓦然回首”，在“灯火阑珊处”领悟真谛。这三种境界启示我们，读书不仅要有明确的目标、有不移的恒心，还要提高读书效率和质量，讲求读书方法和技巧，在爱读书、勤读书、读好书、善读书中提高思想水平、解决实际问题、实现自我超越


***** 光空口而谈、不做实事。

1. 临渊羡鱼,不如退而结网.
2. 先到为君,后到为臣.莫道君行早,更有早行人.
3. 一年之计在于春,一日之计在于寅,一家之计在于和,一身之计在于勤.
4. 有田不耕仓廪虚,有书不读子孙愚,
5. 仓廪虚兮岁月乏,子孙愚兮礼义疏.
6. 使口不如自走,求人不如求己.
7. 十年窗下无人问,一举成名天下知.
8. 枯木逢春犹再发,人无两度再少年.未晚先投宿,鸡鸣早看天.
9. 

孔子登东山而小鲁，登泰山而小天下。

衣带渐宽终不悔，为伊消得人憔悴。
——柳永《蝶恋花·柳永》

渡过难关
山重水复疑无路，柳暗花明又一村。

——陆游《游山西村》

长风破浪会有时，直挂云帆济沧海。
——李白《行路难

众里寻他千百度。蓦然回首，那人却在，灯火阑珊处。
——辛弃疾《青玉案·元夕》

世事漫随流水，算来一梦浮生。
——李煜《乌夜啼·昨夜风兼雨》

世事一场大梦，人生几度新凉。
——苏轼《西江月》

春风得意马蹄疾，一日看尽长安花。(京都花)
——孟郊《登科后》 ------开着汽车


仰天大笑出门去，我辈岂是蓬蒿人。
——李白《南陵别儿童入京》 -----一种自信

千淘万漉虽辛苦，吹尽狂沙始到金。
——刘禹锡《浪淘沙》

望岳_百度汉语

作者：杜甫

岱宗夫如何？齐鲁青未了。
造化钟神秀，阴阳割昏晓。
荡胸生曾云，决眦入归鸟。
会当凌绝顶，一览众山小。

**** 华能的认识
***** 企业使命
****** 企业使命

把公司建设成为
为中国特色社会主义服务的“红色”公司；
注重科技、保护环境的“绿色”公司；
坚持与时俱进、学习创新、面向世界的“蓝色”公司。

****** 企业核心价值观

坚持诚信，注重合作(可以改为多方合作)；
不断创新，积极进取；
创造业绩，服务国家。

****** 企业目标

建设成为国际一流上市发电公司

****** 企业责任

为社会提供充足、可靠、环保的电能；
为股东创造长期、稳定、增长的回报；
为员工营造建功立业、全面发展的氛围。

****** 企业精神

千言万语、千辛万苦、千方百计的敬业精神；
逢山开路、遇水搭桥的开拓精神；
自找差距、自我加压的进取精神；

****** 企业作风

敢为人先，敢为人所不能的创新精神。
善开拓，讲效率，重信誉，勤俭办事。


***** 1. 公司简介
:PROPERTIES:
:ID:       fa79b9f5-cd09-4b04-af60-c50b73161410
:END:

1985年创立至今(华电是1958年)
****** 三大业务
1. 电源开发、投资、建设、经营和管理
2. 电力(热力)生产和销售
3.金融、煤炭、交通运输、新能源、环保相关产业及产品的开发、投资、建设、生产、销售
4. 实业投资经营即管理

中国华能集团有限公司（简称中国华能）是经国务院批准成立的国有重要骨干企业。

　　中国华能注册资本349亿元人民币，主营业务为：电源开发、投资、建设、经营和管
理，电力（热力）生产和销售，金融、煤炭、交通运输、新能源、环保相关产业及产品的
开发、投资、建设、生产、销售，实业投资经营及管理。

　　中国华能从1985年创立至今，在30多年(2019年刚好33年了,的确该改改)的发展历
程中，为电力工业的改革、发展和技术进步提供了丰富经验；为电力企业提高管理水平、
提高经济效益发挥了示范作用；为满足经济与社会发展的用电需求、实现国有资产的保
值增值做出了重大贡献(分三个方面进行论述)。公司坚持方向明确、科学发展，不断创
新、保持领先，多方合作、互利共赢(企业价值观)，逐步形成了“为中国特色社会主义服
务的红色公司；注重科技、保护环境的绿色公司；坚持与时俱进、学习创新、面向世界的
蓝色公司”的企业使命和“坚持诚信、注重合作,不断创新、积极进取,创造业绩、服务国
家”的核心价值观等具有华能特色的企业价值理念。

　　中国华能致力于建设具有全球竞争力的大企业集团。截至2017年底，公司境内外全
资及控股电厂装机容量达到1.7182亿千瓦(2015年1.6063亿千瓦，总体是增长的)，为电
力主业发展服务的煤炭、金融、科技研发、交通运输等产业初具规模，公司在中国发电企
业中率先进入世界企业500强，2017年排名第289位(2016年排名第217位)。

　　 
　　“十三五”是我国全面建成小康社会、实现第一个百年奋斗目标的决胜阶段(大背景下
介绍)，也是公司综合实力达到世界一流企业的关键时期，公司将继续高举中国特色社会
主义伟大旗帜，认真学习习近平总书记系列重要讲话和治国理政的新理念、新思想、新战
略，紧紧围绕统筹推进“五位一体”总体布局和协调推进“四个全面”战略布局，全面落实
创新、协调、绿色、开放、共享五大发展理念，践行“三色公司”使命，坚持“三个一”总
体要求，努力提升“三个能力”，着力构建“三个中心”新机制，转方式、调结构、提效益
，促发展、强素质、创一流，推进公司做强做优做大，领先进入具有全球竞争力的世界一
流企业行列(企业目标)，为全面建设小康社会做出新的更大的贡献。


中国华能集团有限公司的中文全称：中国华能集团有限公司
　　中文简称：中国华能
　　英文全称：China Huaneng Group Co., Ltd.
　　英文简称：CHINA HUANENG
　　英文缩写：CHNG
　　中国华能集团有限公司法定住所：北京市西城区复兴门内大街6号
　　邮 编：100031
　　电 话：（010）63228800
　　传 真：（010）63228866

***** 中国华能清洁研究院

中国华能集团清洁能源技术研究院有限公司（简称清能院）是中国华能集团公司直属的清洁
能源技术研发机构。主要从事煤基清洁发电和转化、可再生能源发电、污染物及温室气体减
排等领域的技术研发、技术转让、技术服务、关键设备研制和工程实施。

清能院重点研发方向涵盖近零排放燃煤发电、煤气化及煤基清洁转化、CO2捕集利用和封存
、大型循环流化床锅炉、低质煤高效利用、水电、风电、太阳能发电、海洋能发电、生物质
能发电、发电新材料、能源系统设计优化、页岩气和煤层气开发等技术领域。截止2018年5
月底，清能院已拥有国家授权专利574件，其中发明专利175件，人均专利数为5.17项，在
未来科学城各央企研究院中排名第一。发表论文210篇，其中SCI和EI收录论文66篇。出版
专著5部，制定行业标准11项。承担国家科技项目34项；获得科技成果50余项，其中，国家
科技奖2项，省部级科技奖17项，集团公司科技奖28项。

清能院拥有一流的科研平台，是“国家能源煤清洁低碳发电技术研发（实验）中心”、“国家
能源水能高效利用与大坝安全技术研发（实验）中心”、“煤基清洁能源国家重点实验室”以
及“中美清洁能源联合研究中心”的重要依托单位。还建成了“温室气体减排北京市重点实验
室”和“北京市低质清洁高效利用技术研发中心”。清能院积极参与国家产业联盟的创建，目
前参与了“二氧化碳捕集、利用与封存产业技术创新战略联盟”及“国家700℃超超临界燃煤
发电技术创新联盟”两个国家级创新战略联盟的创立，并成为联盟核心成员。

清能院承担多项国家重点国际技术合作项目，在国家科技部和国家能源局等部门的指导下，
负责“中-澳清洁煤技术合作项目”、“中-意CCS技术合作项目”和“中-美清洁能源联合研究
中心-清洁煤技术合作项目”。与国际知名研发机构和能源企业进行了广泛深入的交流与合
作，先后与美国劳伦斯利弗莫尔国家实验室（LLNL）、美国劳伦斯利伯克利国家实验室（L
BNL）、澳大利亚联邦科工组织（CSIRO）、美国麻省理工学院（MIT）、美国西弗吉尼亚大
学（WVU）、美国肯塔基大学（KU）、加拿大CAME和挪威Sintec等国际知名研究机构建立了
长期合作的关系；与美国杜克能源公司（DukeEnergy）、美国电力公司（AEP）、法国电力
公司（EDF）、加拿大SaskPower 电力集团、意大利电力公司（ENEL）和巴西电力公司等国际大型能源公司合作开展清洁煤
发电和CCS技术合作；与美国EmberClear公司和美国Powerspan公司等公司合作，推广煤
气化、CO2捕集和CFB技术。通过国际合作，提升了自身的水平，扩大了清能院在能源技术
方面的国际影响力，也极大地促进了华能自主技术进入国际市场。

***** 你对风电的看法 [#B]                                        :@NCEPU:
:LOGBOOK:
CLOCK: [2019-01-11 周五 15:31]--[2019-01-11 周五 15:42] =>  0:11
:END:

                    :PROPERTIES:
                    :CREATED: [2019-01-11 周五 15:31]
                    :END:
                         
                    
你做了那么多的风电相关的内容，你觉得现在风电行业在哪些方面需要改进？
从一个学生的角度来说这个问题有点大！ 国内的企业都在做比如远景的只能叶片
叶片加长，海上风电，以及加装涡发生器， 以及学术领域做的极端工况比如闪电、
结冰等。

而我在做的多轴角运动模型，他真的是能做什么？有什么用？ 不敢说有什么用，
但我觉得对于认识动态过程的气动特性有帮助，对翼型的优化设计有帮助。

要持续性的学习……

你觉得你的成就是什么？经过这几年的工作

也就是你觉得自己的成长有哪些! 你经过哪些挑战,并让你得到了什么!


如果遇到一些特殊情况，你要怎么处理?

**** 火电的认识

***** 1. 发电机失磁后对机组本身和电力系统有什么影响?
****** 对发电机的影响,主要表现在下面四个方面

1. 因为发电机失磁，出现转差，在转子表面将感应出差频电流。差频电流在转子
   回路中产生附加损耗，使转子发热加大，严重时可使转子烧损。特别是直接冷却
   高利用率的大型机组，其热容量裕度相对降低，转子容易过热。
2. 失磁发电机转入异步运行后，发电机的等效电抗降低，由系统向发电机送进的
   无功功率增大，失磁前带的有效功率越大，转差也越大，等效电抗就越小，由
   系统送来的无功也越大。因此在重负荷下失磁，由于定子绕组过电流，将使发电机
   定子过热。
3. 异步运行中，发电机的转矩有所变化，因而有功功率要发生严重的周期性变化，
   使发电机、转子和基座受到异常的机械力冲击，使机组的安全受到威胁
4. 失磁运行时，定子端部漏磁增大，使端部的部件和边段铁芯过热。
****** 对电力系统的影响，主要表现在以下三个方面

1. 不仅不能向系统输出无功功率，反而还要从系统吸收无功功率以建立磁场，这就使得
   系统出现无功差额
2. 如果系统中无功功率储备不足，将会引起系统电压水平下降
3. 由于其他发电机要向失磁发电机提供无功功率，可能造成系统其它的发电机过电流。
   失磁的发电机的容量在系统的所占比重愈大，这种电流愈严重。如果其他发电机因过
   流愈严重。如果其它发电机因过流而保护动作跳闸，将会使系统无功差额更大，造成
   系统电压进一步下降，严重时将会因电压崩溃而造成系统瓦解.

***** 2. 异步电动机的低压启动和降压启动有什么优缺点
异步电动机直接启动：启动电流一般为额定电流的4~7倍。害处：大功率电机的启动会对电
网造成冲击，直接全压启动在启动瞬间的转矩非常大，会对电机内部损伤（比如发电机组发热，优点就是非常方便。
降压起动的优点：不会有直接启动的缺点。启动有缓坡时间，不会引起继电保护误操作。

***** 3. 标准物质的最主要三个特征
均匀性、稳定性、溯源性构成了标准物质的三个基本要素

其具体特征有: 
1. 量具作用
2. 特性量值的复现性
3. 自身的消耗性
4. 标准物质品种多
5. 比对性
6. 特定的管理要求
   
***** 4. 灰对火电厂的影响
主要两个方面的影响
1. 燃烧不正常。灰分增加，炉膛燃烧温度下降。煤的燃尽度差，排灰量增大
   机械不完全燃烧损失增加，飞灰和灰渣带走的物理热损失增加。同时由于
   炉膛温度降低，使煤粉着火困难，引起燃烧不良，严重时引起熄火
2. 事故率增高。燃用多灰分煤还会增加锅炉受热面的污染、积灰，从而导致
   排烟温度身高，排烟温度升高，排烟热损失增加，降低了锅炉运行的经济性。
   因此，从燃烧稳定和安全运行、经济考虑，固态排渣炉燃用的灰分不宜超过
   40%
   
***** 5. 再热的意义?为何超高压机组都使用再热

蒸汽中间再热系统：将蒸汽从汽轮机的中间级引出，到锅炉再热器中重新加热，
然后送回汽轮机下一级继续做功的系统。其目的是在提初压力的情况下，使
汽轮机尾部蒸汽的湿度不知过大，保证汽轮机长期安全工作。根据压力提高的
程度，可装设一次或二次中间再热系统。近代火电厂为提高热经济性，锅炉
汽轮机组多为超高压(13Mpa)以上压力，故多采用蒸汽中间再热系统。

***** 6. 称职优秀电力员工，须做哪些?

安全稳定运行时发电厂完成任务的保证。当发电生产同安全发生矛盾时，必须坚持
生产服从安全的原则，包括以下四点(按照时间顺序, 中间两个设备，运行设备和发电设备)

1. 机组启动中发现异常情况时，应按规程处理，绝不可强行启动不符合启动条件的机组
2. 运行设备发生故障，要认真检查、测试、系统分析原因。不可不经检查、测试就恢复
   投运
3. 在发电设备发生异常运行，达到紧急停机条件时，应按规程规定果断将机组停运，防止
   事故扩大
4. 未经总工程师批准，不得将电气、热机主保护退出运行。电厂所有设备主保护必须定期
   检查校验。

   提高安全意识，做到凡事安全第一，这是安全基准。要有过硬的专业技术，这是技术基础。要有强烈的工作责任心，工作要负责，这是做好工作的关键。

***** 7. 火电厂安全生产的重要意义?火电厂的主要安全威胁?

安全生产意义从两个方面(作用和经济)进行论述
1. 火电厂生产的工艺特点使电厂必须将突发事故作为工作中的重点
   加以预防，如果发生生产不安全不仅会影响对外供电，更严重还会
   造成严重的人身伤害、设备损害
2. 搞好企业的安全生产工作，也是火电厂提高企业自身经济效益的重要
   保障。搞不好安全生产工作，必然影响生产任务的完成，加大成本开发，
   降低市场竞争力

火电厂是燃烧梅或其他物质，产生蒸汽，蒸汽通过汽轮机带动电机发电（更细致
描述： 燃料进入炉膛后燃烧，产生的热量将锅炉里的水加热，锅炉内的水吸热
而蒸发，最后变成高温、高压的过热蒸汽，这种蒸汽经管道送往汽轮机，使汽轮机
旋转，汽轮机带动发电机转子一起高速转动，切割磁感线，从而发出电来。所以
火力发电厂的生产过程主要就是一个能量转换过程，即燃料化学能-->热能-->
机械能->电能，最终将电送出去。高温高压蒸汽在汽轮机内膨胀做功后，压力温度
降低，由排汽口排入凝汽器并被冷却水冷却凝结成水，凝结水集中在凝汽器下部由
凝结水泵送至低压加热器和除氧器，经初氧后由给水泵将其升压，再经高压加热器
送入锅炉，如此循环发电, 回热系统三高四低一除氧)


   
**** 风轮的认识

***** 你对新能源风力发展的认识

　　能源、环境是当今人类生存和发展所要解决的紧迫问题。常规能源以煤、石油、天然气
为主，它不仅资源有限，而且造成了严重的大气污染。因此，对可再生能源的开发
利用，特别是对风能的开发利用，已受到世界各国的高度重视。

 风电是可再生、无污染、能量大、前景广的能源，大力发展风电这一清洁能源已成为世界
各国的战略选择。我国风能储量很大、分布面广，开发利用潜力巨大。近年来我国风电产业
及技术水平发展迅猛，但同时也暴露出一些问题。风能是一种干净的、储量极为丰富的可再
生能源，它不会随着其本身的转化和利用而减少。自20世纪70年代末以来，随着世界各国
对环境保护、能源短缺及节能等问题的关注，大规模利用新能源风力发电来减少空气污染、
减少有害气体的排放量。中国西北、华北北部、东北及东南沿海地区有丰富的风能资源。根
据中国对能源及环境保护可持续发展计划的实施，随着中国新能源风力发电技术的更新及风
电场的不断扩大，到‘2015年，全国总装机规模将达到1×107 kW(2018年约180GW 。
 2017 年，弃风问题有所缓解，全国风电设备平均利用小时 1,386 小时、同比提高 135 小时

http://www.chyxx.com/industry/201803/622893.html 2020约为220GW,年均增长20GW)总结我国风电现状及其技术发展，对进一步推动风电产业
及技术的健康可持续发展具有重要的参考价
值。

2017年上半年全国弃风率为13.6%,比去年同期约下降7个百分点。大部分弃风限电严重地
区形式有所好转，其中新疆、甘肃、辽宁、吉林、宁夏弃风率下降超过10个百分点

另外，为尽快解决弃风问题，2017年11月15日，国家发改委和能源局联合印发《解决弃水弃
风弃光问题实施方案》，《方案》提出总体目标，2017年可再生能源电力受限严重地区弃风状
况实现明显缓解。甘肃、新疆弃风率降至30%左右，吉林、黑龙江和内蒙古弃风率降至20%
左右。其他地区风电年利用小时数应达到国家能源局2016年下达的本地区最低保障收购年
利用小时数(或弃风率低于10%)。各能源管理部门要及时总结解决弃风的工作成效和政策措
施，并提出后续年度解决弃风的工作目标，国家发改委和能源局组织评估论证后确认各省(
自治区、直辖市)年度工作目标，确保弃风电量和限电比例逐年下降。到2020年在全国范围
内有效解决弃风问题(政策性的鼓励，没有说具体的技术解决方案)


***** 海上风电的需求

2016年《风电发展“十三五”规划》提出到2020年全国海上风电开工建设规模达到10.05GW，力争累计并网容量达到5GW以上的目标。并将总量目标拆解至各省份，其中重点推动江苏、浙江、福建、广东等省的海上风电建设，到2020年四省海上风电开工建设规模均达到百万千瓦以上。积极推动天津、河北、上海、海南等省(市)的海上风电建设。探索性推进辽宁、山东、广西等省(区)的海上风电项目。截止2016年底，全国海上风机并网规模为1.63GW，预计2017年至2020年新增装机复合增速为15%。

5) 核准未建风电项目115GW，未来三年风电年均新增或达31GW。截止2017年底，我国核准未建风电项目为114.6GW。根据国家能源局的风电电价调整方案，上述项目均需要在2020 年前开工建设，以获得0.47-0.60 元/千瓦时的上网电价，否则上网电价将被调整为0.40-0.57元/千瓦时，预计2017H1-2020 年均风电新增或达31GW。

https://baijiahao.baidu.com/s?id=1597047929910887097&wfr=spider&for=pc

***** 一篇文章

****** 一、我国新能源风力发电的现状 

　　2005年2月，我国国家立法机关通过了《可再生能源法》，明确指出风能、太阳能、水
能、生物质能及海洋能等为可再生能源，确立了可再生能源开发利用在能源发展中的
优先地位。2009年12月，我国政府向世界承诺到2020年单位国内生产总值二氧化碳排放
比2005年下降40%～45%，把应对气和变化纳入经济社会发展规划，大力发展包括风电
在内的可再生能源与核能，争取到2020年非化石能源占一次能源消费比重达到15%左右。
随着新能源产业成为国家战略新兴产业规划的出台，风电产业迅猛发展，有望成为我
国国民经济增长的一个新亮点。 

我国自上世纪80年代中期引进55kW容量等级的风电机投入商业化运行开始，经过二十几
年的发展，我国的风电市场已经获得了长足的发展。


到2009年底，我国风电总装机容量达到2601万kW，位居世界第二，2009年新增装机容量
1300万kW，占世界新增装机容量的36%，居世界首位[1，2]。可以看出，我国风电产
业正步入一个跨越式发展的阶段，预计2010年我国累计装机容量有望突破4000万kW。从
技术发展上来说，我国风电企业经过“引进技术—消化吸收—自主创新”的三步策略也日
益发展壮大。随着国内5WM容量等级风电产品的相继下线，以及国内兆瓦级机组在风电市
场的普及，标志我国已具备兆瓦级风机的自主研发能力。同时，我国风电装备制造业
的产业集中度进一步提高，国产机组的国内市场份额逐年提高。目前我国风电机组整机
制造业和关键零部件配套企业已能基本满足国内风电发展需求，但是像变流器、主轴轴
承等一些技术要求较高的部件仍需大量进口。因此，我国风电装备制造业必须增强技术
上的自主创新，加强风电核心技术攻关，尤其是加强风电关键设备和技术的攻关。 

****** 　　二、新能源风力发电的技术发展 

　　新能源风力发电技术是涉及空气动力学、自动控制、机械传动、电机学、力学、材料
学等多学科的综合性高技术系统工程。目前在风能发电领域，研究难点和热点主要集
中在风电机组大型化、新能源风力发电机组的先进控制策略和优化技术等方面。 

******* 　　1.新能源风力发电机组机型及容量的发展 

　　现代新能源风力发电技术面临的挑战及发展趋势主要在于如何进一步提高效率、
提高可靠性和降低成本。作为提高风能利用率和发电效率的有效途径，新能源风力发
电机
单机容量不断向大型化发展。从20世纪80年代中期的55kW容量等级的风电机组投入商
业化运行开始，至1990年达到250kW，1997年突破1MW，1999年即达到2MW。进入21
世纪，兆瓦级新能源风力机逐渐成为国际风电市场上的主流产品。2004年德国Repowe
r即研制出第一台5MW风电机，Enercon开发出第二代直驱式6WM风电机，预计2013年
单
机容量将突破15MW[1，3]。从世界范围来看，1.5MW-2MW的机型占世界机组容量的比
例，已从2007年的63.7%飞速上升到80.4%；而在我国，2005年风电场新安装的兆瓦级
风电机组占当年新装机容量的21.5%，而2009年比例已经上升到86.86%。这表明容量
风电机组已经成为我国风电市场上的主流产品。 

******* 2.新能源风力发电机组控制技术的发展 
　　控制技术是新能源风力发电机组安全高效运行的关键技术[5，6]，这是因为： 

　　1）自然风速的大小和方向随着大气的气压、气温和湿度等的活动和风电场地形地
貌等因素的随机性和不可控性，这样新能源风力机所获得的风能也是随机和不可控的
。 

　　2）为使风能利用率更高，大型新能源风力发电机组的叶片直径大约在60m-100m之
间，因此风轮具有较大的转动惯量。 

　　3）自动控制在新能源风力发电机组的并网和脱网、输入功率的优化和限制、风轮
的主动对风以及运行过程中故障的检测和保护中都应得到很好的利用。 

　　4）新能源风力资源丰富的地区通常环境较为恶劣，在海岛和边远的地区甚至海上
，人们希望分散不均的新能源风力发电机组能够无人值班运行和远程监控。这就对新
能源
风力发电机组的控制系统可靠性提出了很高的要求。 

　　因此，众多学者都致力于深入研究新能源风力发电的控制技术和控制系统，这些
研究工作对于新能源风力发电机组优化运行有极其重要的意义。计算机技术与先进的
控制
技术应用到风电领域，并网运行的新能源风力发电控制技术得到了较快发展，控制方
式从基本单一的定桨距失速控制向变桨距和变速恒频控制方向发展，甚至向智能型控
制发
展。 　　定桨距型新能源风力机指桨叶与轮毂的连接是固定的，即桨距角固定不变，当风
速变化时，桨叶的迎风角度固定不变。失速型是当风速高于额定风速，利用桨叶翼型
本身所具有的失速特性，即气流的攻角增大到失速条件，使桨叶的表面产生涡流，将
发电机的功率输出限制在一定范围内。失速调节型的优点是简单可靠，当风速变化引
起输
出功率变化时，只通过桨叶的被动失速调节而控制系统不做任何控制，使控制系统大
为简化。其缺点是叶片重量大，桨叶、轮毂、塔架等部件受力较大，机组的整体效率较
低，也使得这些关键部件更容易疲劳磨损。 

　　变速恒频新能源风力发电机组是近年来发展起来的一种新型新能源风力发电系统
，其转速不受发电机输出功率的限制，而其输出电压的频率、幅值和相位也不受转子
转速
的影响。与恒速风电机组相比，它的优越性在于：低风速时能够跟踪风速变化，在运
行中保持最佳叶尖速比以获得最大风能；高风速时利用风轮转速的变化调节新能源风
力机
桨距角，在保证风电机组安全稳定运行的同时，使输出功率更加平稳。变速恒频新能
源风力发电机组通过励磁控制和变桨距调节来实现最佳运行状态。变桨距是根据风速
和发
电机转速来调整叶片桨距角，从而控制发电机输出功率，由传动齿轮箱、伺服电机和
驱动控制单元组成。随着风电控制技术的发展，当输出功率小于额定功率状态时，变
桨距
新能源风力发电机组采用OptitiP技术，即根据风速的大小，调整发电机转差率，使其
尽量运行在最佳叶尖速比，以得到理想的输出功率。变桨距新能源风力发电机组的优
点
是：输出功率平稳，在额定点具有较高的风能利用系数，具有更好的起动性能与制动
性能，能够确保高风速段的额定功率。 

******* 3.新能源风力发电机组控制策略的发展 

　　风能是一种能量密度低、稳定性较差的能源，由于风速、风向的随机性变化，导致
新能源风力机叶片攻角不断变化，使叶尖速比偏离最佳值，新能源风力机的空气动力
效
率及输入到传动链的功率发生变化，影响了风电系统的发电效率并引起转矩传动链的
振荡，会对电能质量及接入的电网产生影响，对于小电网甚至会影响其稳定性。新能
源风
力发电机组通常采用柔性部件，这有助于减小内部的机械应力，但同时也会使风电系
统的动态特性复杂化，且转矩传动模块会有很大振荡。目前，对新能源风力发电机的
控制
策略研究根据控制器类型可分为两大类：基于数学模型的传统控制方法和现代控制方
法。传统控制采用线性控制方法，通过调节发电机电磁转矩或桨叶节距角，使叶尖速
比保
持最优值，从而实现风能的最大捕获。对于快速变化的风速，其调节相对滞后。同时
基于某工作点的线性化模型的方法，对于工作范围较宽、随机扰动大、不确定因素多
、非
线性严重的风电系统并不适用。 

　　现代控制方法主要包括变结构控制、鲁棒控制、自适应控制、智能控制等[7，8]
。变结构控制因具有快速响应、对系统参数变化不敏感、设计简单和易于实现等优点
而在风
电系统中得到广泛应用。鲁棒控制具有处理多变量问题的能力，对于具有建模误差、
参数不准确和干扰位置系统的控制问题，在强稳定性的鲁棒控制中可得到直接解决。
模糊
控制是一种典型的智能控制方法，其最大的特点是将专家的知识和经验表示为语言规
则用于控制，不依赖于被控制对象的精确的数学模型，能够克服非线性因素的影响，
对被
调节对象有较强的鲁棒性。由于新能源风力发电机的精确数学模型难以建立，模糊控
制非常适合于新能源风力发电机组的控制，越来越受到风电研究人员的重视。人工神
经网
络是以工程技术手段来模拟人脑神经元网络的结构与特征的系统。利用神经元可以构
成各种不同的拓扑结构的神经网络，它是生物神经网络的一种模拟和近似。利用神经
网络
的学习特性，可用于新能源风力机的低风速的节距控制。 
****** 　　三、存在的问题及展望 

　　尽管近年来我国风电产业得到了迅猛的发展，但同时也暴露出众多的问题。 
　　首先，我国尚未完全掌握风电机组的核心设计及制造技术。在设计技术方面，我国不
仅每年需支付大量的专利、生产许可及技术咨询费用，在一些具有自主研发能力的风
电企业中，其设计所需的应用软件、数据库和源代码都需要从国外购买。在风机制造方面
，风机控制系统、逆变系统需要大量进口，同时，一些核心零部件如轴承、叶片和齿
轮箱等与国外同类产品相比其质量、寿命及可靠性尚有很大差距。其次，我国风电发展规
划与电网规划不相协调，上网容量远小于装机容量。风电发展侧重于资源规划，风电
场的建设往往没有考虑当地电网的消纳能力，从而造成装机容量大，并网发电少的现状。
2009年新增装机容量中1/3未能上网，送电难已经成为制约风电发展的瓶颈。最后，我
国风电的技术标准和规范不健全，包括风机制造、检测、调试、关键零部件生产及电场入
网等相关标准亟需建立和完善。因此，展望我国未来的风电产业发展，必须加强自主
创新掌握核心技术；必须加大电网建设力度，合理规范风电开发；必须加大政策扶持力度
，建立健全完善统一的风电标准规范体系。 

　　人类社会已进入21世纪，在新千年开始之际，热门正面临着一系列重大的挑战，全球
经济发展，人口迅速增加，需要提供更多的食物、住房和原料，因而对能源的需求量
也不断增加。在过去20年中，全世界能源消耗量增加了40%，其中85%以上使用的是矿物
燃料。这些矿物燃料燃烧时要产生大量温室气体，全球单是CO2排放量每年就超过
500亿吨，而且还在不断扩大。形成的酸雨造成土壤退化，危害动植物。全球气候变暖可
能会产生灾难性后果，必须采取坚决措施，减少温室气体的排放。因此，治理环境污
染，已成为当务之急。同时，矿物燃料的储藏量是有限的，按目前探明的储藏与开发速度
的比例计算，地球上可再开采的能源，石油为40年，天然气约为60年，煤炭为200
年。如不采取有效措施，到本世纪中叶，人类必将面临矿物燃料枯竭的严重局面。为了减
少大气污染、保护人类生态环境、保证能源的长期稳定供应，必须实施可持续发展战
略，逐步改变现有的能源结构，大力开发利用新能源。这已成为各国的共识。 

****** 参考文献： 

[1]陈永祥，方征.中国风电发展现状、趋势及建议[J].科技综述，2010（4）：14-19. 

[2]张明锋， 邓凯，陈波等.中国风电产业现状与发展[J].机电工程，2010，1（27）：1-3. 

[3]党福玲，朝克，贾永.我国风电产业发展现状浅析[J].经济论坛，2010（12）：58-60. 
[4]韩永奇，韩晨曦.中国风电产业的发展与前景[J].新材料产业，2010（12）：8-10. 

[5]王超，张怀宇，王辛慧等.新能源风力发电技术及其发展方向[J].电站系统工程，2006，22（2）：11-13. 

[6]许洪华，郭金东.世界风电技术发展趋势和我国未来风电发展探讨[J].电力设备，2005，6（10）：106-108. 

[7]张新房，徐大平，柳亦兵等.新能源风力发电技术的发展及相关控制问题综述[J].华北电力技术，2005（5）：42-45. 

[8]马昕霞， 宋明中，马强等.新能源风力发电系统控制技术的研究.上海电力学院学报[J].2005（3）：205-209. 


**** 工程制图

**** 深度学习
* 二网
:PROPERTIES:
:ID:       8188bdbf-e40e-465e-9568-2249b1aa9f16
:END:
** 国网
:PROPERTIES:
:ID:       5c24330a-357b-45d4-a184-bbad16a7338e
:END:
*** 董事、总经理、党组副书记
:PROPERTIES:
:ID:       2c3b9444-7f63-459a-948e-4268d43359b5
:BRAIN_PARENTS: 3f1de670-24d1-4258-8cb6-40d791f197b4
:END:

寇伟
**** 副总经理
:PROPERTIES:
:ID:       d7bc4160-25b1-4ebd-b1ea-3dc69025f2ba
:END:

韩君、刘泽红、张智刚
**** 副总经理、党组成员
:PROPERTIES:
:ID:       efb01e90-612b-40da-bd60-e502904e5e9a
:END:

刘国跃、 杨晋柏
**** 总会计师、党组成员
:PROPERTIES:
:ID:       8f5c36cf-5d7d-4136-b1c7-2e1f1c30e58f
:END:

罗乾宣
**** 中央纪委驻国家电网公司纪检组长、国家电网公司党组成员
:PROPERTIES:
:ID:       9c82ca85-90c3-4ce8-a43e-e3e517080241
:END:

黄德安
**** 党委副书记、副总经理
:PROPERTIES:
:ID:       4908b466-4e7a-4af6-96f9-3dac3c70bb8f
:END:

辛保安
*** 董事长、党组书记
:PROPERTIES:
:ID:       3f1de670-24d1-4258-8cb6-40d791f197b4
:BRAIN_CHILDREN: 2c3b9444-7f63-459a-948e-4268d43359b5
:END:

舒印彪
** 南网
:PROPERTIES:
:ID:       d752efe6-8871-46c1-8579-79d01b6279c8
:END:
*** 董事、总经理、党组副书记
:PROPERTIES:
:ID:       85f03828-bf5e-4460-863f-9166e14a4df5
:END:

曹志安
**** 党组成员、党组纪检组组长
:PROPERTIES:
:ID:       6a9a697a-e797-41bf-bbe5-d4d5e5d68b23
:END:

杨志宏
**** 党组成员、副总经理
:PROPERTIES:
:ID:       c02bb4f1-2333-44b5-9c5a-6b01b8e960f4
:END:

贺锡强,陈允鹏
**** 党组成员、总会计师
:PROPERTIES:
:ID:       6a2d2fe9-218e-4239-8ac1-b801a2ea1c8f
:END:

文利民
**** 党组成员、副总经理
:PROPERTIES:
:ID:       67937aee-3dd5-435c-93f7-f7975ac1f56b
:END:

毕亚雄
**** 党组副书记、副总经理
:PROPERTIES:
:ID:       58659906-6386-48c6-9e27-45499d2b8450
:END:

史正江
*** 党组书记、董事长
:PROPERTIES:
:ID:       12ebf867-2ba7-4065-ae62-8fad03f907b7
:END:

李庆奎
