** <Practical Common Lisp> <2015-05-03 Sun>                                     :BOOK:
 :PROPERTIES:
 :Title:    
 :Author:  
 :Year:      
 :Publisher:
 :END:
 Comments:
* 2017
** 2017-09 九月
*** 2017-09-13 星期三
**** Org Manual <2017-09-13 周三>                                      :BOOK: 
     :PROPERTIES:
     :Title:    org-capture
     :Author: org developers
     :Year:
     :Publisher:
     :END:
   Comments: good
**** Living Emacs <2017-09-13 周三>                                    :BOOK: 
     :PROPERTIES:
     :Title:    Living Emacs
     :Author: df
     :Year: 2010
     :Publisher:
     :END:
   Comments:
* 2018
** 2018-10 十月
*** 2018-10-06 星期六
**** 你的灯还亮着吗?(Your lights on?) <2018-10-06 周六>             :BOOK: 
 :PROPERTIES:
 :Title:   发现问题的真正所在 (Are your Lights on?: How to figure out what the problem really is?)
 :Author:  唐纳德.高斯 杰拉尔德.温伯格
 :Year:     1990 
 :Publisher: Dorset House Publishing
 :END:
 Comments:

本书关注的是如何把握解决问题的大方向,教会你解决问题时要注意些什么,而不是教你解决具体问题(具体问题具体解决)

 共20个故事20个道理,被分在6个主题之中,下面是主题和道理:

***** Q1: 问题是什么?

****** C1.一个问题?

****** C3. 你的问题是什么?

问题是你期望的东西与现实体验的东西之间的差别,尤其是你感觉到的任何不顺都是问题
***** Q2: 这个问题是什么?(clean question, clear discrimination)

不要把别人的解决方法当成问题的定义,作者要表达的是当别人要你协助解决问题时,
你要要求拿到的是整个问题,而非他们已经解决到自己完成不了的那个部分.
也就是不能病人说头疼就医头,脚疼就医脚.
如果你太轻易的解决了别人的问题他们永远不会相信你解决了真正的问题(即使你确实解决了.)


别把解决方法认为是问题的定义-尤其是自己的解决方法.这句话与本段A的区别在于,
这个问题并不是别人的问题而是在解决你自己问题的时候,不要把问题用你的解决方法来定义,
因为这样会很大程度上限制你解决问题的灵活性.解决问题所用的方法也将是你最熟悉的而非最合理的那个方法
<2018-10-06 16:47> 我发现我有点这样的缺点，对问题定义不清，虽然我解决了那个问题。

你永远不能肯定你已经有了一个正确的定义.即使在问题完成了以后.因为正确是基于你所得到的信息的,
而你永远不可能确定是否掌握了所有的信息,
而即使掌握了对信息筛选以及对有效性的顾虑也会让你永远不能肯定你是否有了一个定义.
              虽然如此,但你永远不要放弃对他的追求.
***** Q3: 什么是真正的问题?

问题最难的部分就是去意识到他的存在.

****** 对不相称的忽视
每种解决方法都会带来新的问题:因为无法有个精确的定义所以带来新的问题自然不可避免.
所以作者建议对于问题的理解中,要想出至少

****** C9. 在特定层面上考虑问题

人无法处理问题原因常常有二,问题的答案空间太大或是无法建立可行的答案空间.
而其实前者并非我们找不到好的答案只是我们懒而已.故作者建议在面对问题束手无策时,
可以适当的加一些不同的条件来辅助思考.这样也更有助于多角度的看待一个问题.
而最后作者也指出在你解决问题一筹莫展时,也该回头看看你对问题的理解是否正确

游泳： 游就是漏出来，泳就是潜在底下


****** C10. 注意你表述的意思

一旦你用文字来表述一个问题,要确信在每个人的脑中他都是同一个意思.
而作者给出了,先用改变需要重读的词组,再对关键的词组查字典的方式.
且最好把定义和指代副词替换成你认为他的含义.而当难以用文字表达时试着用公式图片等其他方式来,

<2018-10-06 17:11>注意语言的二义性

***** Q4: 这是谁的问题?

****** C12. 校区的停车场

****** C13. 隧道尽头的等

有时问题的受害者,并不是没有能力去解决问题,他们只是暂时没有意识到问题的存在而已.
这时作为旁观者清的你,不帮则眼看其受苦,帮太多则会弄巧成拙,
最好的方式则是用一句善意的提醒.让他意识到问题的存在即可.

***** Q5: 问题是从哪儿来的?

问题的本质原因常常是多种多样的,你需要的是从现实中不断的收集证据从可能的原因中找到真正的那个原因,
而不是根据自己的主观臆断就把原因归结于天性命运等不可解因素,
虽然也存在这种可能,但这种懒惰的做法让你永远解决不了问题.


不论你成不承认很多问题的本质是来自于你自己.不论是定义错问题,还是误判了情况


书法： 书写工具、纸张、笔、墨

左手再动，右手也在动，这叫做书法

朴素的读(素读): 不联想，只是读书中的内容。
https://www.youtube.com/watch?v=7Rj5CmKFVyE


这世界上有两种人,给人找事做的人和做事的人.而为了体现自己的价值,
前者经常无中生有的制造些麻烦给后者,对于后者来说这些要他们解决的问题,
根本就不是问题.而作者给出的建议是戳穿诡计后不要浪费你自己的时间,
保持尊重的推掉他并把荣誉留给制造麻烦的人

****** C16. 做事情和享受荣誉

***** Q6: 我们真的解决问题吗？(问题到底是什么?)

长期的学校教育把我们培养成了一个急着去解决问题,但其实并不确切知道问题是什么的人.
作者指出当你确切知道问题是什么时,解决问题便会变得异常的容易.
而这种人定义问题常会犯解决式提问的方式,即他解决问题时需要什么,
他便问什么,另外值得一提的是故事中的雇主和解决问题者都犯了这个错误.
而作者也得出了,不管人们看上去如何但是他们很少知道他们要的是什么,直到他们所要求的东西.

表达:
    用故事表达,风趣但有写晦涩是这本书的特点,要多看几遍才能了解这些自命不凡的老头像说些什么,
值得一提的是序篇很标新立异,表述的便是一个解决问题的过程,解释了些本书中谈到过的道理,很有意思.
****** 一项获得技术领先奖的任务


鱼是最后一个看到水的。重复的刺激会导致反应越来越小。
适应性允许我们忽略环境中恒久不变的东西。当我们考虑问题的时候，
我们习惯了的东西总是倾向于从思考中被忽略。

如果沉浸在问题当中，解决者就会冒着忽视其它重要因素的风险。



读万卷书等同于万里路

或者行万里路等同于读万卷书(条条大路通罗马 All ways to Rome


https://www.jianshu.com/p/35dfd08f6a50



说话不要端着，让别人听着舒服。。。

素读(大量的知识储备为前提)，就是听作者的声音。。。。。

https://www.youtube.com/watch?v=7Rj5CmKFVyE

棋王 树王 孩子王
https://baike.baidu.com/item/%E9%98%BF%E5%9F%8E/3938048?fr=kg_qa


一个国家的希望就是知识分子的能力和责任。

政协委员崔永元在分组讨论会上连续开了几个大炮，
第一炮开向奶粉，
第二炮开向政府报告谈成绩不谈问题，
第三炮开向卖地强拆追求GDP。
这几炮，真可谓炮炮惊雷
https://www.youtube.com/watch?v=diN75ViXuGA

统治者希望他的大多数子民是unclever
肉食者鄙，历代都有

https://www.zhihu.com/question/20887788 如何评价崔永元？
https://www.zhihu.com/question/62986733 如何评价崔永元辞去璞谷塘所有职务并退出所有股份？
https://www.zhihu.com/question/60453677 如何评价崔永元的170万高山黑木耳？



国难显忠良，家贫思贤妻
https://www.youtube.com/watch?v=LRUq_cv7aZU

历代：
马上打天下不能马上治天下

http://rufodao.qq.com/a/20160107/045304.htm

马下得用读书人，贤者充满智慧的人。

汉朝是中国历史上继短暂的秦朝之后出现的朝代，分为“西汉”（公元前202年—公元9年)
与“东汉”(公元25年—公元220年）两个历史时期，西汉为汉高祖 刘邦 所建立，建都长安；
东汉为汉光武帝刘秀所建立，建都洛阳。东汉末年，世分三国，其中就有汉王朝后裔刘备的蜀汉，这么说的话，汉朝一脉相承，就有：
刘邦（汉高祖）→刘恒（汉文帝）→刘启（汉景帝）→刘胜（中山靖王）→刘贞（陆城亭侯）→刘昂→刘禄（漳侯）→
刘恋（沂水侯）→刘英（钦阳侯）→刘建（安国侯）→刘哀华（广陵侯）→刘宪（缪水侯）→刘舒（祈邑侯）→
刘谊（祈阳侯）→刘必（原泽侯）→刘不疑（丰灵侯）→刘惠（济川侯）→刘雄→刘弘→刘备


刘备 才能也不比 刘邦差啊 刘备从走街卖草鞋的干到蜀国皇帝 
刘邦当年起码起点比刘备高 刘邦起码还是个乡长里，
2个人都有共同点 
都姓刘 
建国前都被人追着屁股打 
    刘邦被项羽追着屁股打 打到自己父亲都被烹杀 
    刘备 被曹操追着屁股打 打到刘备丢下老婆孩子逃命 
    项羽和曹操都是将相之后，虽然历史上刘备没有刘邦伟大 但是刘备也是有名的君王啊，
    2个姓刘的都讲义气 都能容人 会用人 2人都可说是人中之龙 谁也不比谁差 

刘邦手下有韩信 张良 萧何 
刘备也不差啊 还有5虎将诸葛亮啊 

有一点刘邦不及刘备 就是刘邦害死了大功臣韩信 
也没听说刘备有陷害自己手下大将的 相反刘备很疼爱自己部将呢 
还有一点刘邦不如刘备 刘备手下有2位神一样千古威名的人物 诸葛亮 和 关羽 中国古代也没几位能比这2位名气威望高的了 进一步托升刘备


陆贾是楚地之人，在刘邦起义的时候，就跟随他，进献自己的智谋。
熟悉历史的人都知道刘邦是一个性格张扬、厌恶儒生的人，他看到有人戴儒生的高帽子，
就要把那帽子摘下来，往里面撒尿，而陆贾恰好是个儒生。他在刘邦身边，常常引用《诗》、
《书》进言，刘邦自然不会给他好脸色。有一次他骂陆贾道：“我的天下是在马上得来的，
要《诗》、《书》有什么用！”而陆贾从容不迫地说道：“您从马上打下来的天下，难道还能在
马上治理天下吗？商汤、周武王都是像您一样取得天下，却用安定的手段来维护政权，文
武并用才是保证政权长久的办法。春秋时期吴王夫差、智伯穷兵黩武最终走向灭亡，而秦
国一直严刑峻法，终于灭亡在赵高手里。倘若秦国在统一天下后，推行仁义，取法先圣，天下又哪里轮得到陛下来执掌！”


这一番议论，让刘邦为之语塞。他知道自己鄙视儒生的做法是有错误的了，面带惭色，
对陆贾说：“那请你为我写一本著作，说明为什么秦国失去了天下，而我为什么得天下，
还要有古代国家成败兴亡的例子。”陆贾于是接受了请求，写了十二篇文章，一篇一篇
写在竹简上，上奏给刘邦，而每一次上奏，刘邦看了都交口称赞，左右看了刘邦高兴的
样子，也山呼“万岁”，于是《新语》一书就此问世。当然陆贾不但信奉儒家思想，也吸收了
黄老道家的许多思想，主张清静无为，推行仁义，减轻刑罚，并广求人才，他的政治观点
深刻的影响了汉初政治，给广大民众休养生息的时间，最终让社会走向了安定。


中国朝代顺序表：夏、商、周[西周、东周(春秋、战国)]、秦、汉(西汉、东汉)、
三国时期(魏、蜀、吴)、晋(西晋、东晋)、五胡十六国、
南北朝[南朝(宋、齐、梁、陈)、北朝(北魏、东魏、西魏、北齐、北周)]、
隋、唐、五代(后梁、后唐、后晋、后汉、后周)、
十国[前蜀、后蜀、吴、南唐、吴越、闽、楚、南汉、南平(荆南)、北汉]、
宋(北宋、南宋)、辽、西夏、金、元、明、清。中国历代皇帝顺序表

http://k.sina.com.cn/article_6629948294_18b2cfb8600100cpwm.html


安史之乱成为唐代历史的转折点

乱前是唐朝的鼎盛时期，乱后的唐朝则进入了衰落阶段，并最终走向了灭亡。
安史之乱中“安”、“史”指的是安禄山与史思明，他们都是少数民族将领，又都是唐朝的节度使

到玄宗晚年，更以一人充任多镇节度使，并将大部分兵力布置在节度使地区。
当时全国兵员总数为57万，而边兵竟有49万之多，中央兵力空虚，地方武力
坐大，给节度使发动叛乱创造了条件


安禄山是居住在当下辽宁朝阳的胡人，据说他的祖先是从今伊朗迁移而来

Explain what is specially different by your method?

Give sufficient detail that the reader can reproduce what you did.

Method should be an easy section to Paper just say what you did
