#+OPTIONS: num:nil toc:nil
#+REVEAL_TRANS: linear
#+REVEAL_THEME: jr0cket
#+Title: 安在天给阿炳讲捕鱼的故事
#+Author:  Ye Zhaoliang
#+Email: yezhaoliang@ncepu.edu.cn

Situation:
咱们家乡老一点的人都知道，日本鬼子由于在南京遭到一定抵抗，死了不少人，然后采取了一系列报复行动，比如南京大屠杀就是这样的。打到我们家乡时，报复还在继续，所以日本鬼子在我们家乡是要遭天杀的，烧杀抢掠奸淫，什么坏事都干尽了。不过，我们家还好，多亏父亲消息灵通，预先安排母亲带着我和两个妹妹，回无锡乡下生活了一年多。我们住的村子就在太湖边上，村子上的人多半以捕鱼为生，我有个堂伯是当地出了名的捕鱼好手。到了冬天，鱼都沉入湖底，出去捕鱼的人经常空手而回，惟独我这个堂伯，从来没有空着手回来过，他的竹篓里总是装着你想像不到的大鱼或者其他鲜物。究其缘故，是我堂伯冬天捕鱼有个绝活：他能从水面上冒出的纷繁凌乱的水泡中，一眼瞅出哪些是冬眠的鱼吐出的(深水捕鱼高手)，哪些不是；对着"鱼泡"一网包下去，鱼就成了瓮中之鳖。
 阿炳侦察敌台给我的感觉就是这样的，他不但能从众多水泡中看出哪些是鱼泡，而且还能从各式各样的鱼泡中分辨出各式各样的鱼类。换句话说，他不但知道哪些水泡下面有鱼，而且还知道是什么鱼，鲤鱼，鲫鱼，还是其他什么鱼(阿炳的能力)。 无疑，阿炳比我堂伯还技高一筹(夸奖)。 

我说过，求胜心切是当时701所有人的心情。在阿炳进机房之前，没有人知道怎么样去赢得胜利，然而自阿炳进机房的这天起，大家似乎都一下明白了。这一天，阿炳在机房坐了18个小时，抽了4包烟，找到敌台3部共51套频率，相当于每小时找3套，也相当于之前那么多侦听员十多天来收获的总和。 令人惊叹的兴奋又难以置信！ 以后的一切是可想而知的，阿炳每天出入机房，几乎每天都在不断刷新由他自己创造的纪录，最多的一天，即第十八天，他共找到敌台5部、频率82套。奇怪的是，这天之后，他每天找台（频率）的数量逐日递减，到第二十五天，居然一无所获。第二天一个上午下来又是这样，劳而无功。下午，阿炳已经不肯进机房了，他认为该找的电台都找完了。 是不是这样呢？ 

墙上挂有进度统计表，一目了然，到此为止，我们一共找到并控制对方86部电台共计1516套频率。其中阿炳一个人找到的有73部电台，共1309套频率，占电台总数的86%，频率总数的87%。但根据我们掌握的资料看，至少还有12部电台还没有找到，而且这都是对方军界高层系统的电台。 一边是不容置疑的资料，表明还有敌台尚未找到；一边是绝对自信又绝对值得信任的阿炳，认为所有敌台都找完了。怎么会出现这种情况？局长临时召集各路专家开会，分析研究，结果大家一致认定，只有一种可能就是：未显形的敌台肯定以一种与已有敌台截然不同的形式存在着，否则阿炳不会一下变得束手无策的。 但到底是什么形式呢？ 无人知晓。 会议无果而终。
 第二天，我没有带阿炳去机房，而是要了部车，决定带他去散散心。我原想去桑园肯定是最好的，但找了又找没见着，最后去了一个果园。我不会告诉你是什么果园的，因为写成书后，有人知道了，就有可能缩小我们701的地区方位，是南方，还是北方？是东南，还是西北？在那里，就是在果园里，我们一边呼吸着新鲜空气，一边闲聊着。阿炳像个孩子一样的高兴，而我则更像一个心事重重的父亲。结束游园之前，我跟阿炳讲起了我堂伯捕鱼的故事，故事的下面这部分是我有意编造的，很神话，而阿炳却听得如醉如痴，信以为真。 我说："有一年冬天，我堂伯照常去湖里捕鱼，但接连几天都看不到湖面上冒出"鱼泡"（conflict)）。我堂伯由此认为湖里的大鱼都被他抓完了，于是就呆在家里，靠吃鱼干过日子。

但有一天，他孙子去湖边玩耍，看见成群的大鱼在岸边浅水区"游来游去"(新现象）。

这就是说，湖里还有很多的大鱼，只不过这些大鱼都变狡猾了（新观点），它们知道沉在湖底总有一天要被我堂伯识破，所以都离开湖底，游出深水区，来到岸边的浅水区。岸边虽然寒冷，但空气充足，用不着使劲呼吸就可以存活。不使劲呼吸就不会冒出气泡，不冒气泡，我堂伯自然就找不着它们。"

 我就这样让阿炳明白：我们至少还有12部敌台尚未找到，为什么找不到？是因为它们"像狡猾的大鱼一样"躲起来了，躲到我们想不到的地方去了。躲去哪里了？现在只有一个办法可以找到它们，但这个办法很难，我问阿炳想不想试一试

