* 创意
** Introduction
*** subtree
*** open the link
** review of related literature
** description of study
** methodology
** results and analysis
**  conclusion [%]
** tomato time
番茄时间的本质，是充当时间度量。
用来表示今天一天的工作，用了几个番茄时间，明天能否多工作一个番茄时间来减少无意义的消磨。
在具体项目上，例如：上次写一篇文章用了3个番茄时间，这次能不能提高效率，争取2个番茄时间。
这也就是为什么番茄时间反复强调必须25分钟，且中间不能打断的原因。
** 深入任何一门学科能力                                              :太阳:

#+BEGIN_SRC org
    我写“入门书”而不是“进阶书”的另外一个原因，就像爱因斯坦说的：
                如果你不能向一个六岁小孩解释清楚一个问题，那么你其实并不真的懂。
  我在大学里见过太多讲不清楚问题的教授，中国的美国的都有，后来我发现那是因为他们自己都没弄明白。没有非常深入的见解，
  你是不可能把深奥的东西解释清楚的。反过来，试图把一个问题向完全不懂的人讲清楚，也会大大加深你自己的理解。
  看了我的『怎样写一个解释器』而学会解释器的人都会明白，
  我的理解程度在全世界处于什么地位。没有成千上万次写各种各样解释器的试验，失败和领悟，你是不可能理解到那种程度的。

    深入理解任何一门学问的关键，不是试图去回答越来越“高级”，越来越复杂的问题，而是试图去回答最基础的问题，
  反复地问自己最基础的问题…… 爱因斯坦之所以能发现相对论，不是因为他去思索看起来高级的难题，而是因为他去思索
  一个最基本的问题：时间是什么？其他人觉得这问题很傻，时间不就是一秒一秒过去的那个东西吗？现在是半夜两点，那就是时间！
  然后这些人就永远没机会发现相对论了。同样的，深入理解计算机科学的关键，不是去学习云计算，大数据或者区块链，
  而是去思索最最基本的问题：“计算是什么？” “程序是什么？” “函数是什么？” “变量是什么？” “抽象是什么？” …… 
  你觉得自己知道这些问题的答案吗？那请你再想一想！

    实际上直到 20 世纪初，全世界没有一个数学家真正的理解“函数是什么？” 这个如此基础的问题。
  这些人却天天都在用“函数”这个词，以至于他们的定理和证明里面出现各种奇怪的错误。
  直到 1904 年 Frege 写了这篇论文“What Is A Function?” 这种情况才得到了改善。数学发展了几千年，
  居然没有人真的理解如此基础的，天天都在用的概念。他们以为自己明白了，所以根本没有仔细思考过它是什么。
  就像我们从来没思考过什么是时间，却天天都在谈论“需要多少时间”一样。
#+END_SRC

 [[file:~/.emacs.d/GTD/orgBoss/Journal/20180308::*21:35%20%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E5%8E%9F%E5%88%99][21:35 设计模式原则]]
**  伟大的网格剖分 
第一次o剖由于球网格存在问题，所以第一个面不能选择

以后则都应该选择第一个面， 这种控制网格划分方式,有时候看之前的block无法看出来！！必须得融汇贯通，包括辅助线的选取。
 [[file:~/.emacs.d/GTD/orgBoss/newgtd.org::*%E6%9C%BA%E8%88%B1%E5%81%8F%E8%88%AA%E7%BB%98%E5%88%B6%20<2017-11-15%20%E5%91%A8%E4%B8%89%2010:44>][机舱偏航绘制 <2017-11-15 周三 10:44>]]
** 笔记的用处 
笔记只能帮助你整理，但是他并不能让你一下子产生idea

不能完全依赖笔记，太依赖笔记，相当于idea没进入过你的脑海里，"只有进入你脑海里的东西才是终身受用!"

笔记可以帮助你梳理idea，要想产生idea一定还得再自己脑海里转转!


笔记可能带给你一个迷惑，觉得记了就会了，其实不见得，还是得学习
** 反复阅读你的writing，并进行修改 

通过反复阅读你的text system，从而改进你的语言表达能力，进而提升你对事物的认知(还是认识?)

在这个过程需要持之以恒的能力
 *
 [[file:~/.emacs.d/GTD/orgBoss/Note/notes.org::*tags%20important%20%5B#B%5D][tags important {#B}]]
** 专注 
专注、专业在于你要做到事情(只有一件一方面最重要的事情)，保持持续的时间投入，
能对各种干扰源说"不"; "不"这个字很重要

有得有失，不说"不",那么就失去你对最重要事情的投入, 完成一件事源自于过程，
而非源自于瞬间! 结果的瞬间必然是来自春种夏浇秋收割,这是恒古不变的道理，
也许只有明白这个过程，你的人生才能得到进一步的生活。

叶：认识源于过程，专业始于投入
<2018-09-29 22:06> 依然有用
这阶段、今年、五年内你要做什么最重要的一件事情呢？
** 任何一项研究，都得写明背景 

一项研究，如果能对idea的来源写的让读者一目了然，那么就值得好好思考，进而不断衍生出新的想法

而背景是什么？ 历史长河中不断演变的过程，对相似问题的整体描述，并提出新的观点想法等

据研究，2.5~4D范围内对风力机气动性能的CFD计算不会有太大的影响，但是如果是尾流则会
有所影响！尾流至少得5D左右！
**  我们总是活在别人的不同级别的抽象级别中 

说不定我们就被定义某人的abstract类中，肆无忌惮的划分，不去管你的感受

当然这就决定人们对于world的看法，对于life的看法

当你自己也局限于那个level的时候，的确，你就是划分为那个abstract类中

world是复杂的，过度的abstract，会导致过度的分级，进而导致传输出现问题，(上行下效有时候是好事，但是有时候也是坏事), 口是心非，阳奉阴违，表里不一、
消极怠工。 也许你就是那个abstract也无所谓， 每个人都是可以evolving的，可以跳出不同的abstract圈， 只要你不要影响到
那个圈子里面的人即可！


 [[file:c:/Users/yzl/perl/testProcessOut.pl::#%20);]]
** 不同的时代总是有灰色交易 

国家会默许这些灰色收入，但是有一点特别重要！决不能吃独食，要团伙作案(大家一起吃，别人也不会把你抖出去)

不同的时代，总会那么的机会，让你吃惊、胆寒，需要你去把握，当然也有一些老狐狸在看着你！

当然这些机会总是给那些消息通天的人得到！这也是为什么大家不断地参与聚会、交流信息


善守者，别人不知其所守，守其不备，功其乏！
善攻者，敌不知其所攻，


善攻者，敌不知其所守，善守者，敌不知其所攻
进攻的人，可以让敌人不知道该防守什么地方；善于防守的人，可以让敌人不知道该从什么地方进攻

兵者，诡道也!
** reviewer 's 态度 

review your life!Review your path! Review your time!

*** 1. 关于we

**** 一般
qAdd a comment to the complex algorithm you wrote.
**** 好
With such a complex algorithm, we should add a clarifying comment.
**** 更好
With such an innovative approach to solving this problem, should we add a clarifying comment explaining it,
 or should we break out some of the expressions into functions that we could name to help the reader follow
 the logical flow?

*** 2.关于问号(golden rule)
**** 2.1一般
Inline this function, please.
**** 2.2较好
Since the function called is a single line, and only called here, let’s inline the function.
**** 2.3最好
Do you think that since this function is a single line, and only called here, 
would it be more understandable to inline it?

通过增加更多的"why"，一方面为大多数人解惑，另一方面也在提高团队的质量

Sensei is the one who is further ahead on the path;
      which characterizes a teacher as one who can look back along a path and say,
 
     “Watch your step there, that’s a particularly slippery spot. 
     If you do fall, it’s okay, because I fell too.” 

It’s a compassionate approach to teaching, which we should all adopt.
Use your intelligent to become an sensei!


Start including more "why" into your explaination, including code examples, deep links into
style guide, and references to existing code that may illustrate your point!


While they all state the same request, I’d argue the last one is the nicest. 
1. First, since we’ve already established that we might not have all the context and be wrong, 
asking a question not only softens the request, but initiates a dialog, not a response.[1.softens the request! 2.initiates a dialog]

2.The other feature it brings is an ego-supporting back-door for both of you. 
Since this isn’t a direct command, the author may be more willing to accept the comment, 
but if the author responds with clarifying information why it should stay, you too, 
are more apt to accept it since it was just a question.

This tip is golden, and I often rephrase all my suggestions as questions.

linter 是 一类 小程序 的总称，它不像编译器程序那么大，它可以用来检查程序的 文体，语句 的 语法，句法错误，并即时标注和指出来
（例如，把声明了但没使用的多余变量指出来，把错误语句 变成黑体）， 是程序开发的辅助工具
** 讲课，意味着找出你所知道的知识并解释给别人，这是学习的最佳方法

一方面首先你需要通过自己(透过自身)扎到问题的答案，来提高自己的能力。

这比简单的问别人须付出更多的努力，不过你正是靠这个来积累经验，同时避免过度地打扰同事。
 
A master never stop learning
** suggest, input, filter, target(SIFT) 

For this article, I will use terms suggestion and completion to
mean subtly different concepts. I'll also use terms explore and
filter in describing various phases in user interaction.

***  Suggestion
Offer the user some suggestions that help explore the space of choices. 
(metaphor: avoid the blank sheet of paper syndrome).
***  Completion
Filter the available choices based on user input with the goal of 
reaching the target as rapidly as possible.
***  Explore
User does not necessarily know what he is looking for, but expects to be 
able to recognize what he wants from the displayed choices.
***  Target
User knows exactly what he wants, e.g., filename, or function-name, 
but would still like to get there with the fewest possible number of 
keystrokes, along with the needed memory aids to guide the decision.


Note that in practice, suggestions and completions work
hand-in-hand, with the visual display playing a central role in
guiding the user through the pace of available choices. In a typical
user interaction session, the space of suggestions gets filtered by
user input to produce the available completions (choices) for the next
round of user input — think of this as a
Suggest/Input/Filter/Target (SIFT) interaction loop. Similarly, explore and
target type activities typically go hand-in-hand, with explore
serving as a memory-aid for locating the target.



#+BEGIN_EXAMPLE
Effective Suggest And Complete In An Eyes-Free Environment
1 Executive Summary
Emacs has always provided a wealth of techniques for rapid keyboard
input (abbrev, dabbrev, hippie-expandand completion come to mind)
alongside a rich collection of tools for navigating among open
buffers. And these affordances have significantly increased over the
last few years with the arrival of packages like ido, company,
helm etc., each replete with different strategies for rapid task
completion such as flex and fuzzy matching. This article investigates
these tools in an eyes-free environment, specifically in the context
of Emacspeak and rapid task completion. I've not investigated every
possible package in this space — instead, I've picked a collection
of packages and techniques that have worked well in an eyes-free
context. Finally, the ultimate metric I use in each case is the time
to successful task completion — since at the end of the day, that's
the only metric that counts when it comes to user productivity.

2 Terminology
For this article, I will use terms suggestion and completion to
mean subtly different concepts. I'll also use terms explore and
filter in describing various phases in user interaction.

Suggestion
Offer the user some suggestions that help explore the space of choices. 
(metaphor: avoid the blank sheet of paper syndrome).
Completion
Filter the available choices based on user input with the goal of 
reaching the target as rapidly as possible.
Explore
User does not necessarily know what he is looking for, but expects to be able to recognize what he wants from the displayed choices.
Target
User knows exactly what he wants, e.g., filename, or function-name, but would still like to get there with the fewest possible number of keystrokes, along with the needed memory aids to guide the decision.


Note that in practice, suggestions and completions work
hand-in-hand, with the visual display playing a central role in
guiding the user through the pace of available choices. In a typical
user interaction session, the space of suggestions gets filtered by
user input to produce the available completions (choices) for the next
round of user input — think of this as a
Suggest/Input/Filter/Target (SIFT) interaction loop. Similarly, explore 
and target type activities typically go hand-in-hand, with explore
serving as a memory-aid for locating the target.


3 Tasks Where Suggestions And Completions Help Speed Up Task Completion
Here are exemplars of tasks that I perform often and where I require
all the help that Emacs can provide in completing the task as rapidly
as possible:

File Navigation
Navigating to and opening a file — either code or prose.
Content Navigation
Jump to a specific location (section, function, class/method, or pattern-match) in that file.
Buffer Navigation
Jump to an already open buffer in a long-running Emacs.
If that buffer existed — but has since been killed (by
midnight for example), then re-open that buffer.
I do everything in Emacs, so open buffers include a large
number of ORG and LaTeX documents, Web Pages opened in EWW 
(news sites, documentation, blog articles), IM Chats (I use
jabber), Mail Buffers — both open folders and previously
sent messages, and much, much more.
Media
Easily launch media streams including local and streaming media.
EBooks
Open (or jump to an already open) EBook to continue reading.
Code Completion
Complete function/method-name as I type, with an easy affordance to move among the available choices. The Suggest/Input/Filter/Target interaction loop applies here as well.


Notice that as one performs all of these tasks, every target is an
Emacs buffer or Emacs buffer location. In the case of completion, the
target is a string that gets inserted at the current location.

4 Features Of Eyes-Free Interaction
Using spoken output — as opposed to a rich visual display — has
the following special features and/or drawbacks:

A large visual display can offer the user many choices at a time,
and the eye's ability to rapidly scan these choices makes for an
extremely fast Suggest/Input/Filter/Target loop. As an example, an
interface like helm can display a large number of initial
choices, with the user filtering these down with a few strategic key-presses.
Spoken output takes time — and there is simply no way around
this — speeding up speech-rate helps to a point, but speaking
50 choices very fast does not help the user in the explore
phase. This means that effective filtering and ranking of the available
choices takes on added importance.
More importantly, picking a Suggest/Input/Filter/Target (SIFT)
interaction loop that depends on a large display is sub-optimal
for eyes-free interaction.
Given (2,3), smart filtering, flex/fuzzy matching, and ranking
based on past user behavior take on added importance in an
eyes-free environment. As an aside, I have high hopes in this
area for package prescient — though in my few days of usage,
it has yet to make a difference in my productivity.
For many of the tasks enumerated in the previous section, (2, 3
and 4) make ido with flex and fuzzy matching extremely
effective. In contrast, helm with similar flex and fuzzy
matching (via packages helm-flx and helm-fuzzier) adds little
extra benefit — and the fractional extra time to compute and
display the choices can even lead to a minor productivity hit.
When it comes to writing code with completion, package company
has proven extremely effective. Notice that when writing code,
one rarely if ever resorts to fuzzy matching — this may well
be subjective. Speaking for myself, I cannot think of function
or method names in the context of fuzzy matching — said
differently, it's hard to think xl for function-name
next-line — even though in a given filtering context, xl
might define the shortest path through the available choices to
the target next-line. Given this, emacspeak implements a
company front-end that allows the user to navigate through the
available choices with succinct spoken feedback, and I use those
choices only after I have typed sufficiently many characters to
have a manageable number of choices — said differently, though
package company is set up to trigger after 3 characters have
been typed, I usually end up typing more — and often resort to
dabbrev or hippee-expand to input this longer prefix.
Some of the shortcomings with eyes-free interaction enumerated
above lead to my looking for effective work-arounds that might
well work well outside the eyes-free context, e.g. when the
available choices are too large to fit on a typical visual
display. Interestingly, most of these have also been solved by
mainstream Emacs developers in their never-ending/unerring quest for increased
productivity — package ido and company are excellent exemplars.


Mapping Solutions To Tasks

This section maps the various solutions I use to speed up the tasks
enumerated earlier in this article.

4.1 File And Buffer Navigation
I use package ido with add-ons flx-ido and ido-completing-read+
(formerly ido-ubiquitous) as my primary/only solution for this
task. I've dabbled with package helm — primarily via command
helm-mini but have found almost no use-cases where I did better with
helm. I also use command org-switchb to quickly jump to any of my
open org buffers – since that automatically filters the choices
down for me — I can then get to the org-mode buffer I want with
one or two keystrokes. Notice that in all of these cases, I'm relying
on the fact that I mostly know what I want, i.e., the explore phase
does not start with an entirely blank sheet of paper.

4.2 Content Navigation
Incremental search is your biggest and most effective friend in
effective eyes-free interaction — this simply cannot be stressed
enough. That everything in Emacs is searchable via
incremental-search is a big win for eyes-free interaction. When you
have a large visual display, the human eye is the search interface of
first resort – you typically use a search-command only if the
target is below the fold or far away from the cursor. Because spoken
output takes time, I use isearch even when the target is one or two
lines away.

Structured navigation comes next in my toolbox for navigating content
— imenu for code, and section navigation for documents (org,
LaTeX). I also use command occur to advantage since that provides a
quick way of finding all the desired targets in a document. Given that
program source-code uses indentation for displaying structure,
hbuilt-in command selective-display remains one of Emacs' hidden
treasures with respect to expanding/collapsing source-code.

Finally, I
use a combination of isearch and structured navigation in
org-mode buffres by collapsing the document, and then using
isearch to reveal the desired content fragment.
In the case of LaTeX documents, I use package reftex to
generate a navigation buffer that functions as an interactive table
of contents. 

4.3 Locating And Playing Media
I keep all my music content organized under ~/mp3.
I keep playlist files that contain stream-links to my favorite
Internet streams under emacspeak/media.
The afore-mentioned techniques using ido enables me to launch
local and streaming media with a small number of keystrokes. Once
selected, the content is played via package emacspeak-m-player
which provides Emacs bindings to all mplayer functionality
via that program's slave-mode. In addition, Emacspeak also
implements a smart emacspeak-m-player-locate-media which uses
Emacs' integration with command locate to turn the located
files matching a given pattern into an interactive play-list.

4.4 EBooks
Jumping to already open ebooks is no different than buffer
navigation. I organize all my ebooks under a single directory
tree, and module emacspeak-epub implements a bookshelf that
allows me to organize and browse my collection along various
axies. Finally, Emacspeak implements a light-weight bookmark
facility that works with eww so that I can save my place in an
ebook across Emacs sessions.

4.5 Code Completion
As covered earlier, I use company along with dabbrev and
hippee-expand while writing code. I also use yasnippet to
generate skeleton code. I use auto-correct-mode to
automatically correct repeated errors, and add abbrevs for
commonly occurring typos. 

5 Summary
Emacs' Suggest/Input/Filter/Target (SIFT) interaction loop is just as
effective in eyes-free interaction — in fact more so .
Fuzzy matching when filtering is a big win when working with spoken
output — it leads to faster task completion.
Navigating ones computing environment based on the underlying
structure and semantics of electronic content is a major win —
both when working with a visual or spoken display. The advantages
just become evident far sooner in the eyes-free context due to the
inherently temporal nature of spoken interaction.
Date: 2018-06-22 Fri 00:00

Author: T.V Raman

Created: 2018-06-23 Sat 17:22
#+END_EXAMPLE

 [[brain:7f09c147-afa3-4968-9c59-e9ec56c9695f][Drracket]]
** 永远不要贸然怀疑别人                                               :地球:
永远不要贸然怀疑别人，也永远不要放弃怀疑别人的权利和自主权

最好这时候眼珠子转转

潜伏，哪有那么容易。短期还可以，长期就特别不容易(长期就没有那么容易)

最好隐身办法，尽可能得罪身边每一个人,
要把自己伪装成别人都讨厌的人，人见人厌（朱厌）,扮成一个贪财、无能的小人物，

千人烦万人厌， 有多烦人就多烦人!

一个没有朋友的人是最不容易漏出破绽的
** 亿万字符正在不断在时空空间重组 

字符序列在光亮同道中，不断地重组又消融，然后在光符通道中形成一个灯笼、画廊般的通道！

分段字符组构成一段一段萤火虫般的光亮通道


 [[file:~/.emacs.d/GTD/orgBoss/Note/notes.org::*%E5%AD%97%E7%AC%A6%E7%BB%84%E5%92%8C%E5%A4%9A%E9%80%89%E7%BB%93%E6%9E%84%E7%9A%84%E5%8C%BA%E5%88%AB][字符组和多选结构的区别]]
** which direction point north?  we need to each other to grow!

总是有个时间找不到北！不知道往哪里走！

We need (to help) each other, if we wanna(are going to) grow!
如果我们想要成长，就要互相帮助!
Where our needs do not make us week(我们的需求，并不会让我们显得脆弱) ,they
make us fully humans(而会展示出我们真正的人性)




We ask for the requirment, not because we need the mercy, Everyone can benefit from the world full with mercy!
(mercy不意味养成饭来张口 钱少伸手)

We all benifit from living in a more compassionate time(day)
经济自由度(economic freedom)


当你遇到困难时，很矛盾想退缩时，想到我这句话也许能帮上你

“爸|妈，不用害怕。你老了，现在是我牵着你们的手往前走了。”


身后有余忘缩手，眼前无路想回头。

小说《乾隆皇帝》里乾隆有一段话，说他为什么要不停地折腾。
他说，他也知道射出去的箭，总有会落地的一天，强弩之末，势不能穿鲁缟。
他所能做的，就是拼命把弓拉满，力求让射出去的箭，晚一点落地。（开弓没有回头箭）

** 逻辑清楚，分清主次(还欠点火候)

这么大的人，还被人说分不清主次，表现逻辑不清楚！

事情的确是一件事情一件事情去做，但是总得有先后，比如yawAngle=10° 可能比30°更好算些，可以先算
当然前提你可能不知道，于是随意选择任意偏航角进行计算（最好是按照顺序来，逻辑本来体现着一种顺序）

做之前一定得想好了！思考清楚再开始做！

比如三滑移，本身的尺寸应该是偏摆轴在地面上也就是距离旋转轴90m位置处(下移90m)
这点位置很重要，因为会导致旋转方向的切向速度分量发生改变，进而改变局部流动攻角！

切记！切记！

Review: 综述(回看--->Predict预测）
Research: 研究(再搜索==研究)

 [[file:~/.emacs.d/README.md::%E6%9B%B4%E8%AF%A6%E7%BB%86%E7%9A%84%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95%E5%8F%82%E8%80%83%5BWeb-mode.org%5D%5B54%5D]]
** old school and modern feature                                 :emacslisp:

James Gill has a nice tweet about the community of Emacs users:

    I’ve never encountered a community like that of #Emacs users. So many with 10, 20, 30+ years using the tool,
    endless resources and helpful people.
    And so delightfully ‘old school’ and modern at the same time.

An elegant weapon, for a more civilized age.

— James Gill (@IamJamesGill) August 21, 2018

Like most of you, I belong to several tech communities. Not all of them have as nice a reputation.
 The Lisp community, for example, can be notoriously hostile to n00bs.
 A lot of that is residual grumpiness about the fact that the first thing many n00bs do when 
they arrive is suggest some scheme for doing away with parentheses.
 If you heard that as often as the typical Lisper, you’d be grumpy too.

Still, there’s no denying that the Emacs community is exceptionally welcoming to n00bs and that,
 as Gill says, we have a lot of people with extensive experience who are willing to help n00bs as well as more seasoned users.
 We also have folks like Mike Zamansky, Sacha Chua, and Rainer König who spend hours of their own time 
making instructional videos and doing other chores that benefit us all.

I think Gill has it exactly right: We’re old school and modern at the same time.
 Old school because we’re employing an editor that’s older than many of its users 
and modern because that same tool is more powerful and adaptable than its more “modern” competitors.
 In any event, it’s a great community and I’m proud to be a member.

 
old with adaption and modern with more powerful
** 守时是他们的强项 

别小看人(鸡鸣狗盗之人)，守时是他们的强项
 [[file:~/.emacs.d/GTD/orgBoss/newgtd.org::*CFX30%C2%B0%E7%BB%99%E5%AE%9A%E5%81%8F%E8%88%AA%E8%A1%A5%E5%85%85%E8%AE%A1%E7%AE%97%20<2018-06-25%20%E5%91%A8%E4%B8%80%2008:30>][CFX30°给定偏航补充计算 <2018-06-25 周一 08:30>      {100%}]]
** 你只有洗的干净，人家才有吃的欲望 
而如果你洗的不干不净（吃了没病），别人连吃都不想吃

当然别人可能就不好这口也有可能，有些菜只能提供给一些人！

但是洗干净、工作做好，是第一步!
** 协作带来成长 

合作的魅力
*** 不能分享就无法协作 

说到协作，你必然已经很赞成。但是无论体制外宣称要建立生态链，还是体制内高喊牵引分系统，往往还是关起门来当个自给自足的农民，内心的梦想还是想当个土皇上。 

有本事的打天下，把自己的围墙盖到别人的领域里。我们普通人就插个篱笆，保护好自己的一亩三分地。 

协作的好处不常见，协作的风险却无法回避。 

我们说最好的产品，每个系统应当由最优秀的人去做。但是你敢吗？你敢将产品的创意与别人分享吗？你敢让更优秀的人与你竞争吗？ 

经验告诉我们，如果你敢将创意告诉别人，别人会毫不客气地署上他的名字，连个谢谢都不会给你。 

环顾四周，不能与同行分享，怕同行剽窃；不能告诉客户，怕客户泄露给对手；也不能告诉盟友和朋友，在利益的诱惑下，盟友马上变对手，朋友立即变敌人。

你只能在保护的围墙里，扩大自己的队伍，用自家很差的能力，去实现无论如何都不能与别人分享的创意。 

作为企业，所有的研究都要自己做，用自家末流的仿真与末流的实验支持二流的设计，梦想实现一流的创意。作为科研者，即使隔壁就是某专业的大拿，也要自己做，不能敲开隔壁的门求别人。 

我们往往过高估计了创意被剽窃的风险，远远低估了无法分享带来的损失。

 

 

*** 将创意变成公知

也许可以这么做，公开你的创意，把创意告诉同行，告诉客户，告诉对手。快速让所有人知道，谁第一个提出了这个创意。

有100家知道了你的创意，就没人敢谎称是他的原创，这就叫用事实占据正统性。

将自己的创意变成公知，也许是对原创最安全的保护。 

申报专利和版权可以保护一些东西，但是不够。 

最不可取的，就是有选择地告诉个别盟友，叮嘱千万不要告诉别人。你会发现利益面前没有好人。要么谁也不告诉，要么告诉所有人，没有中间道路。 



你的创意被大家知道了，虽然你占据了原创的光荣，但是所有人都成为了竞争对手。 

大家站到了同一个起跑线上，看谁可以最快将创意变成产品。如果你能力不如别人，最后还会输给别人。 

将创意告诉大家，就要接受这个结果。你赌的是你对创意理解最深刻，你对创意最执着，你敢于将竞争的压力变为动力。 

逼迫你与最优秀的团队合作，逼迫你高效率地运行，逼迫你接受批评，逼迫你尊重技术，逼迫你玩命地做到最好，这能说是坏事吗？ 

好创意就应当由好队伍去实现，难道你有了好创意，就有资格让不咋地的队伍去浪费吗？ 

把创意藏在怀里，悄悄自己捅咕，没有最强大的竞争力逼迫你做到极致，没有最优秀的人才与你协作，再好的创意将来也会被别人不咋地的创意超越。 

要对得起好创意，就去呼唤强大的力量与自己竞争，把自己逼迫到拼命的绝境。 

 

 

*** 在竞争中协作

协作是必须的，但是协作还必须竞争，要让整个协作过程就是互相淘汰的过程。 

千万不要一开始上来就分蛋糕，把将来的利益划分得清清楚楚。好像可以避免以后打架，其实将来真的蛋糕出来了，该打架还会打架，但是过程中却失去了互相淘汰的激励。 

优秀的协作者，最初是找到的，后期却是逼出来的。给对方找个虚拟的对手，就能保证对方的积极性。 人性靠不住，最初找个好人家合作，只是减少了后期变卦的风险，给对方找个虚拟对手才是保证协作愉快的良方。

优秀的协作者，最初是谈出来的，后期是培养出来的。谈判桌上的利益终归有限，我多了对方就少了，对方多了我就少了，永远不公平。 

如果让大家说各自贡献了百分之几，再把所有的贡献加起来，肯定大于百分之一百，也许会高达百分之二百、三百甚至一千。人们自恋的程度，会让你大跌眼镜，这个与道德无关，这是人性。 

解决这个问题不是没完没了地谈判，谈判会把大家的注意力，从创造更大的价值，转到争夺更多的利益。 





↘

*** 把成果放大一百倍 

协作的出路，是为协作者培养更大的新蛋糕，让所有的成果分成几份后越分越多。 

几家协作，在最后产品利益之外，还可以获得各自的利益：
材料加工—获得实验数据验证材料特性
实验分析—获得新材料做实验
仿真分析—获得实验数据验证仿真
理论分析—获得实验与仿真的数据
产品设计—获得理论依据与数据支持 

将研究成果共享，所有人从中获利，一份研究成果，不同的专业获得不同的效益，比如提高测量技术、形成仿真软件、申报专业研究项目、建立专业知名度，从中派生出种种成果。而且交叉研究更容易有突破性的发现。 

大家从划分最终产品利益的小圈子，发展到各家打造新蛋糕。逐步培养出来更强大的协作者和更大的利益圈子。 

前方有大协作的多重利益，后面有虚拟对手的威胁，协作可成。
** 对自己要求高，对别人要求低 
很多人活得不开心，都是因为对自己要求低，对别人要求高，其实要是反过来就很好！

对自己要求高，对别人要求低，活得就舒心了
 [[file:~/.emacs.d/GTD/orgBoss/Site/www.site.org::*mastodon][mastodon]]
** Slow down and stop before burning out 

slowdown
slow-down
学会判断的能力 甄子丹《大师兄》, 在失败中成长，而不是在失败中自暴自弃。
之所以谨慎，因为吃过亏，没吃过亏的人，通常是自己过不去，吃过亏长点
记性，反而会一致对外。


Writing code, documentation, helping users
about bugs or helm usage etc., ant it was too much.

I've learned to stop or slow down before burning out. Helm package作者Thierry
Volpiatto一个攀岩爱好者。

在截稿前放慢自己的步调，有时候是一种沉淀。
这也是一种学习。


http://sachachua.com/blog/2018/09/interview-with-thierry-volpiatto/
** 孤独的旅程(I still carry on)---pain
每个人的成长都得伴随着一段孤独的旅程，学会自己寻找方向，自己发现问题，
提出一种方法去解决他。 中国素质教育伴随着太多的考试制度，导致一没有老师
的指点，自己就做不了了，这是很要人命的。

要面对自己的恐惧(face your fear)，要是要心存希望(carry on with hope)。
不要放手(Don't let it go)，别让我失望(don't let me down)
我知道前面还有慢慢长路(I know it is  far way)
我会一直支持你(I'll care you)
知道我无法继续支持你(till I can't go on)
无法承受这份(hold this pain)
我会努力不懈，坚持下去(I still carry on,oh oh, I still carry on)

 https://www.xiami.com/song/1774417231?spm=a1z1s.7154410.1996860241.3.BLxSxJ

It is your job! 不要再次放逐你自己了。

自主学习，自主行动， action by yourself. Independent you, Independent soul, Independent solution.
或者说每个人成长的日子都是追逐独立自主的过程。（Rich Stallman)

你是一个醒着的人？你的灯还亮着？

I'll care you的you代表什么？(你的爱好，你在乎的人，你在乎的事)

 [[file:~/.emacs.d/GTD/orgBoss/Note/notes.org::*%E8%80%81%E5%AE%9E%E4%BA%BA%20%5B#B%5D][老实人 {#B}]]
** 衣服得蕴含有趣-崔哥 (sense of funny)

衣服除了穿和美之外，是不是还得哟一种有趣的味道。

正如写代码也是需要一点有趣的地方

I think that it's extraordinarily important that we in computer science keep fun in computing.
When it started out, it was an awful lot of fun. Of course, the paying customers got shafted 
every now and then, and after a while we began to take their complaints seriously. We began to 
feel as if we really were responsible for the successful, error-free perfect use of these machines.
I don't think we are. I think we're responsible for stretching them, setting them off in new directions,
and keeping fun in the house. I hope the field of computer science never loses its sense of fun. 
Above all, I hope we don't become missionaries. Don't feel as if you're Bible salesmen. 
The world has too many of those already. What you know about computing other people will learn. 
Don't feel as if the key to successful computing is only in your hands. What's in your hands,
 I think and hope, is intelligence: the ability to see the machine as more than when you were 
first led up to it, that you can make it more.

https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-3.html
 
 [[file:~/.emacs.d/GTD/orgBoss/Note/notes.org::*pyqt%20%5B#B%5D][pyqt {#B}]]
** 笨重的大象变小 
 
你的不好的习惯就好像一陀笨重的大象，需要从你的脑海里的
剔除出去。坚持去做你认为该做的事情。默认咒语:"变小、变小
变小，小，小，小",然后"踢出去"

保持良好的习惯，不要让你的惰性指挥着你，学会控制自己。

灵活、变化、趣味是人不可缺少的，过分单调也不是太好。默认
咒语
** 问题分为两部分 

重点：笔记和问题分为人和事两部分(要带着目的，进行倒位和换位 ,倒位是时间思考，换位是空间思考)。

笔记，一定要分开人(你该思考的, 解决方案是什么？ 该怎么干)和事(它的用途，方法，何时用，怎么用，注意点，场景等,它干了什么，优势和劣势)

1. 问人(自己和其他人)
   1. 你该思考什么?
   2. 你的解决方案是什么?
   3. 你该怎么干?
2. 问事(事物本体，以及处于同一问题领域的其他事物)
   1. 它的用途？ 它到底干了什么
   2. 它采用的理论方法?
   3. 他何时被用到？
   4. 它该怎么用
   5. 使用它该注意什么?
   6. 使用他的场景是什么? 和其他工具相比，他有什么优势和劣势?

    
a. 我能否思考清楚我阅读的目的，
b. 并通过阅读主要的重要内容，识别其中哪些是专业问题，并自己提出相关的问题，
c. 最后根据背景内容、背景主题、背景问题，进行改述（简短、清晰、符合总体思想)、重新组织、总结这些信息，
d. 运用图片、模式、节奏、故事的方法进行记忆和可视化？ 


态度就是你之前的处世态度，过去经历。 你的态度就是你的信念、设想、期待以及价值的总和(有四个)。
你的态度就是你看待世界的方式。
因为态度存在很多的设想，设想越多，问题越多，你学习的过程可能就会越多,
所以，你的态度也决定了你能收获、掌握知识的多少。


跳出【或者叫做改变、拓展】你的态度来思考问题【多看看其他人的生活、工作态度，跳出自己狭窄的世界】
学习的态度是不断学习（终生学习就是人的精神)，进行自我教育。以学为乐。不断发现问题、解决问题

博士最别致的特性(也可以叫做态度)就是终生学习的能力。

从哲学观点来看，结论是相对一定条件而言的，结论与条件互为因果关系，
条件（原因）是引起一定现象的现象，结论（结果）是由于条件作用而产生的现象。基于一定的条件推出结论.


   [[file:~/.emacs.d/GTD/orgBoss/Journal/OneJournal.org::*14:31%20%E4%BB%A5%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E4%B8%BA%E6%A0%B8%E5%BF%83%E7%9A%84%E7%AC%94%E8%AE%B0%E8%AE%B0%E5%BD%95%E6%96%B9%E6%B3%95][14:31 以解决问题为核心的笔记记录方法]]
** 学习一个程序的流程                                        :地球:学术:
c语言教学大纲
https://wenku.baidu.com/view/fa095372a417866fb84a8e2e.html
https://www.iqiyi.com/w_19rqrg6xwp.html

数据结构word
https://wenku.baidu.com/view/110e924f19e8b8f67d1cb929.html

把一个程序由不懂到看懂，分三步：(流程、功能、试数，针对于计算机领域)
        1. 流程
        2. 每个语句的功能
        3. 试数
看懂之后，再深入
        4. 看懂以后--去敲程序！不停地敲不停地敲，一遍正确后再敲，再出错再敲！
        5, 日积月累，能力就上来了


对新知识、新对象进行简介，给出他的特点，使用注意情况，运用特定的场合，
明确他的意义，解释他和相似知识点的关系，提出新的方法和概念，简化逻辑过程和使用


都是从它的角度出发,最后两点强调它与问题领域其他对象的关系.

1 Java内省是什么？(它是什么)

2.java内省的特点是什么？

3.使用java内省该注意？

4.java内省主要使用的场所？

5.为什么使用java内省  java introspection存在的意义是什么？

6. java 内省和javaBean 或者Bean类有什么联系？

知识点A
1。 为什么需要A
2。 什么是A 
3。 怎么使用A 【最简答的】 
4。 使用A时注意的问题 
5. A的应用领域（A的运用场景） 
6. A的优缺点


面向对象风格（把A当做一个花生核，你的任务则是填充元组内容)

#+BEGIN_SRC python
  class A
      def __why__
          return "reasons"

      def __what__
          return "What is A"

      def __how__
          return "how to use A"

      def __getAttention__
          return "You must take care sth while you use A"

      def __getApplication__
          return "Other pesons use A"

      def __getBad__
          return "A cannot do sth"

      def __getGoods__
          return "A is good at doing sthjj"
#+END_SRC


函数式风格：

#+BEGIN_SRC python
  print("\n{}\n".format("为什么使用A".next("什么是A").next("怎么使用A").next
                        ("使用A注意什么").next("A的运用场景").next("A的优缺点")))
#+END_SRC

#+RESULTS:


 
 [[file:~/.emacs.d/GTD/orgBoss/Journal/OneJournal.org::*13:24%20ABCD%E5%8E%9F%E5%88%99(%E6%B1%87%E6%8A%A5)--%E6%BC%94%E8%AE%B2%E4%B8%8E%E5%8F%A3%E6%89%8D][13:24 ABCD原则(汇报)--演讲与口才]]
**  每个人都有隐形的时间隧道 
诸葛亮说:"非宁静无以致远"，只有保持长久的注意力，才能完成一个比较有意义的工作，全身心投入一件事情。
把自己变为一束光，投入到时间隧道中(或者时间海洋) 直到完成一件事情，你才能从隧道中出来，每个人都有
一个独立的隐形隧道，只有你自己一个人能够进入
 
 [[file:~/.emacs.d/GTD/orgBoss/Journal/OneJournal.org::*14:31%20%E4%BB%A5%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E4%B8%BA%E6%A0%B8%E5%BF%83%E7%9A%84%E7%AC%94%E8%AE%B0%E8%AE%B0%E5%BD%95%E6%96%B9%E6%B3%95][14:31 以解决问题为核心的笔记记录方法]]
** 变压头阀 

类似限流阀，只在流量迅速改变的时候限压，平时的时候改变很少
国内现在没有。
** 谋定而动 
** 有太多的人在背后设计你？ 

《我在底橙社会中的生活》
一个软件团队在背后，动用大量的人力物力来让你上瘾，爱上它

让你的时间投资该软件。让你的自制力彻底瓦解（whatsoever)

利益永恒？还是兴趣至上？ 还是贪欲无法阻挡？

你的一个paper通常是20min报告，20*100=2000min的准备（你的准备通常是需要更多时间）
背后的工作

那么如何提高自己的自制力？ 我们如何改变自己？ 设计自己？


*** 傻瓜指数?

如果你的傻瓜指数是1天，也就是说你一天内就更新了自己

如果你的傻瓜指数是1辈子，也就是你一辈子都浑浑噩噩的过着

*** 朋友指数?

我身边有多少优秀的新朋友？ 优秀新朋友越多，朋友指数越多

*** 让自己被监督(建立个人品牌，华衫建立个人品牌的意义)
广告的意义，做品牌的价值，被"绑架"的价值,让你的产品受到
舆论最重要的监督，让你的产品持续更新，而不是造假、以次充好。


想要让自己变得更好，不妨事先设计一种方式，让自己被"绑架",比如建立一个github的用户，设计一个项目
让自己广而告之。被“绑架”，被“约束”也许是对我们的帮助

*** 反馈和设计反馈

游戏，它的核心机制，是不确定反馈，在不同的战局会有不同的反馈。
谁点赞、谁评论？ 反馈是一个重要的人体机制。(确定的事情有时候干起来更不激情）


把一个宏大的目标切碎了(说着很难，做起来太不容易）。
心流(heart flow)----切可森米哈赖(心理学家)首次提出。
(沉醉其中，无法自拔，没有感觉到时间的流失)


谁能把目标比作香肠，像切香肠不断切下去，让你能够一步一步的吃完？
而不是给你一坨。（医生职业，做得好，人们鼓励， 厨师职业，好菜，不错，口碑好)


别人喜欢用他们的产品吸引你，可是我偏偏不被吸引，那我们就首先获得了主动权。


*** 每个人心中都有两匹狼

印第安纳州，有一个老人和小孩在对话，
老人说:"每个人的内心里都有两匹狼，其中一头狼奋斗、上进、开心、乐于助人,
另外一头狼阴险、邪恶，臭名昭著,他们每天都在打架着"
小孩问:"那么最后哪条狼赢了"
老人说:"这得看你选择去喂那头狼"(Interesting)
** 不要对自己含糊了

要做的明白，不要敷衍和含糊了。 要做的清楚明白


 
** 不要愤怒那会影响你的判断 
老教父 柯里昂尼 说：“不要愤怒，那会影响你的判断”
不要紧张，那会影响你的判断。

历史教会我们的事：“任何人都可能被kill”

这个视频中心的经典就是一句话:"白道比黑道还要黑。合法的犯罪。"
** 人生总有那么几次极限需要自己去突破 
 
By Mr Kang
 [[file:~/.emacs.d/GTD/phd1.org::*%E5%9F%BA%E4%BA%8E%E5%A4%9A%E8%BD%B4%E8%A7%92%E8%BF%90%E5%8A%A8%E7%9A%84%E6%B0%94%E5%8A%A8%E7%89%B9%E6%80%A7%E5%92%8C%E6%B5%81%E5%9C%BA%E5%88%86%E6%9E%90%E5%A4%A7%E8%AE%BA%E6%96%87%20<2018-06-25%20%E5%91%A8%E4%B8%80%2016:19>][基于多轴角运动的气动特性和流场分析大论文 <2018-06-25 周一 16:19>{3/4}]]
** 观察力，有时候是你必须首先做到的 
 
 [[file:~/.emacs.d/GTD/phd1.org::*YawingForRenewableEnergyChina%20<2018-11-29%20%E5%91%A8%E5%9B%9B%2017:07>][YawingForRenewableEnergyChina <2018-11-29 周四 17:07> {0/6}]]

                    :PROPERTIES:
                    :CREATED: [2018-12-05 周三 10:58]
                    :END:

                    
要学会观察，先别着急，眼观周围环境，你的closure or surrounding environment决定着
你程序是否能够正常运行，要记得你该记住的，这是你的环境变量，你周围的环境变量会
让你的事情变得好办些，比如说副处长办公室在哪里？还需要找谁签字？该怎么跟他说话？
(还比如 泥泞路上停下车来，仔细观察哪边可以涉水，可以平稳通过， 还比如等到人都上来了
再开始走, 小车速大车距目的就是留下更多的时间让你去观察!)

一件事情就是一道程序，只不过是这道程序可能需要各种审核，无非是让y=f(x)中的f变得
更加复杂些，比如还需要找正处签字，还需要找校领导签字等等，为了完成这个程序于是
你需要准备很多材料。生活中的很多事情无非是一道道程序，有些程序很流程，比较简单(干了什么事? 事情有多重要，得到了什么结果)。

有些程序需要时间的配合，需要你的观察，需要你的表演才能进行下去，不要让生活的xyz难倒
你，要去学会观察，逐步执行他们，就好像写一篇文章也是如此，你需要给编辑、给读者需要的
信息，秉着科学的逻辑下，不断填充需要的内容，最后完成这道程序题，可能这套程序题难就在
得琢磨、解释其中发生的事情，但是大部分现在的paper也是数据合成的手段（大白话就是天下
文章一大抄) 

在办理的过程中，任何参与的人员都是其中的变量，这些变量人员可能会对你质疑、否定，但是
别气馁，想要这套程序执行完，一定要去克服其中得变量人员，他们之所以质疑、否定你，是因
这是他们的工作"认真的执行程序的流程"

在万千的程序中，永远是人情这套程序最难执行！虽然我以程序化理解，是因为想直观的去感受
这个世界的边边角角，百态人生。

记住，去观察、去思考、去想象、去设想，去做，落实他们，直到把一道道程序题做完。
** 功成名就 
 
 [[file:~/.emacs.d/GTD/myResearchPaper/DyanmicYawPhaseVi/draft.org]]

                    :PROPERTIES:
                    :CREATED: [2018-12-05 周三 17:06]
                    :END:

当一个人功成名就的时候很难经的起失败，甚至都不敢想象自己失败后的样子，
反而在人生最低谷，什么都没有的时候更容易经历和承受挫折，毕竟什么都没有
所以不怕失去什么。


不过廖凡当然不能把他最精心准备的地图拱手相送，他从办公桌的抽屉里拿出
另外的一份地图仔细研究起来，这一份地图比上一份地图更加详细。这份地图
上竟然标记了这个地区的常住人口数量和粮食经济发展情况。

这地图都是廖凡根据近大半年来搜集的情报分析出来的，当然有很多数据是不
准确的，例如小鬼子抓壮丁或者当地的老百姓逃难，都会造成各项数据的误差，
但是总的来说，这么基础的数据更有利于分析出敌我真正力量的变化，毕竟当地
的人口和经济决定这个地方能够养多少兵，一旦超过了底线，过多的兵力不在是
战斗力，而是破坏力。

小鬼子采取以华制华，尤其是岗村宁次跟参谋本部的简报中写到尽量要给中国人
“尊严”，甚至提出了“讨蒋爱民”的口号，不断分化抗日势力，这简直就是在跟整
个中国争夺人口，一旦中国控制的人口减少，兵源就会减少，可见岗村宁次的险恶用心


不是一个真实的人

心里面的那点傲气和信念

厕所内的人，不着急，然而厕所外人则分外着急
** 文章写作要点 
 
 [[file:~/.emacs.d/GTD/orgBoss/pythonLearning.org::*pyCharm%E5%BF%AB%E6%8D%B7%E9%94%AE%E4%BD%BF%E7%94%A8][pyCharm快捷键使用]]

                    :PROPERTIES:
                    :CREATED: [2018-12-15 周六 17:59]
                   <2018-12-15 20:47> 
                    :End:

                    
一个博士论文得围绕一个主题、一件事
至少达到 1. 干了什么  2. 有多么重要 3. 取得了什么成果

文章写作前的要求

1. 结果是否有实验数据?(实验、计算前就得进行查找)
2. 章节结构前后有什么关联
3. 创新点是结论性的东西？
   干了一件事，有意义的事情(重要，并且没人做过，证明过的)
   一般是：得到了(获得了)  2. 揭示。。。 3. 提出
4. 标题放大，醒目
5. 多图标尺一致，先说图中鲜明特点处，再说顶部、中部、下部
   目的：讲图不要忘文字， 其次把读者引入图中(让读者有一个低门槛进入)
6. 逻辑起点: 先说一条曲线，再说多条曲线(随着。。。增加，。。。增加)

   
**** 意义
1. 提出新的问题
2. 对老问题解决办法
3. 整件事情的了解的知识面更深了
   并引申到PPT中，每张PPT都包含着他的意义

   研究内容（重点讲),包含研究方法(研究目的) 为什么用这种方法
屡清你的逻辑思路，讲述图与图之间的变化，他们存在相同也存在着不同。

*** 词的表述

气动： 2D,3D
绕流机理(3D)
研究了涡发生器的作用和机理(作用太宽泛，可采用绕流机理)
（是否油分离? 没分离的话，涡发生器没作用!)


采用CFD方法在平板边界层流动中，研究了涡发生器的绕流机理

研究了不同尺度的平板边界层的厚度，从而研究涡发生器的绕流机理

要注意公式： [条件|前提] [模型]
  条件:不同尺度    模型：平板边界层

  1. 采用什么method(模型model) ----parameters
  2. 变了几种边界层、多少尺寸
  3. 以...为模型，采用CFD方法，研究了...
     以...为模型，采用实验方法，研究了...
     
研究了不同风速 不至于內叶展的三种涡发生器结构(三角形、矩形、提醒)...
涡发生器结构是条件? 感觉不行， 布置于內叶展的是几何? 感觉不是


加强: 有利于
减弱： 不利于

位置(x,y)  高度(一个Y)  宽度(一个x)

分号表示并列
句号表示一个句子结束

图中特征点、特征物理量随时间变化而得到
随高度、宽度变化。。。。

首次这个词一般是后人评阅时写的语言
一般去掉首次，保留得出了即可



然后这个词指的是另一件事
其次这个词一般是指同一件事情的不同层次


*** 物理量

压力系数是最基本的气动系数,可以通过欧拉方程(势流方程)求解即可

压力系数可以反映欧拉和N_S

总之,黏性和无黏方程都满足压力系数分布

分离点要么从鞍点引出，要么从螺旋结点引出

大攻角会发生前缘分离(风力机叶片很少发生前缘分离，除非失速型风力机,因为稍微大一点，变桨就发生，现在变桨型风力机，一般没有前缘分离


**** 近壁面效果(由于墙的存在，由于边界层的存在)
1. 低Re
2. 高剪切率
3. 二元湍流
4. wall blocking
   
**** 边界层厚度的影响因素
1. 壁面粗糙度
2. 湍流度(层流和湍流有关)
3. 黏性系数(越大越厚)
4. 来流速度
   
   1. 随着Re增大，惯性起主要作用，此时速度增大，回事边界层变薄，损失减小

   2. Re继续增大，此时进入自模化区

   3. 而继续提高来流速度，此时已是高速流动，需用Ma分析高速流动
      Ma>1 会产生激波， 造成强的压强梯度，密度阶跃，会形成很大的损失
      导致边界层变厚！（飞机的边界层厚度)

      也就是整体边界层厚度随着速度增加，逐渐减小，在一定自模化区内保持不变，随后突然变大，处于高马赫数状态
      
一般层流边界层较薄，湍流边界层较厚，转捩边界层居中)
**** 黏性
1.层流黏性(物理黏性)
2. 湍流粘性，分为自身黏性(黏性是一种现象，黏性系数是一种性质(同一工质是一样))
   湍流黏性 miuT=sqrt(tw/ro)  AGS模型定义黏性为f(粘性系数，速度梯度) 如果梯度
   为0，即使有黏性系数，也无黏性
   
分离的两个条件
1. 黏性
2. 一定的逆压梯度
   湍流边界层的黏性阻力大于层流边界层的黏性阻力
   
功率：
从黏性角度影响分析(影响较小) : 网格，y+ ，湍流模型，边界条件，失速模型
从无黏角度(影响较大)  无旋、无涡： 整体几何 尺寸


*** 尖速比
lambda=omega*R/v, 但你的速度越大反而越好模拟，对应低尖速比，此时雷诺数起
主要作用，而高尖速比情况下，速度一般较小，所以黏性起主要作用。而在风力机功率的计算中，黏性的影响主要包括，网格,y+,湍流模型，边界条件，失速模型，可能就是湍流模型
此时会比较难于模拟。

5m/s低风速，不好模拟（由于高尖速比)
*** 湍流模型
SST(k-w)适应外场高湍流度的情况，壁面函数相关(SST的r方程求解转捩长度，theta方程求解转捩位置, 转捩位置加入涡发生器等其他被动控制附件,未分离则不考虑涡发生器，比如负攻角，则不需要考虑涡发生器的影响。)
SA模型更适应低湍流度模型。

DU210: 攻角越大，会使分离提前, alpha=20°，涡发生器小翼的影响较大，alpha越大，基本上不能使涡发生器发挥作用
相对厚度越厚(厚度/弦长) 的翼型，失速攻角减小，最大升力系数减小，越容易发生流动分离。

*** 湍流度

翼型升阻力系数发生质的变化

由于分离泡生成（局部散热能力不同)，在高湍流度流动会发生明显失速现象

湍流度Tu的增加加强了来流边界层的扰动，使得层流转捩提前
从而促使分离泡形成（分离泡是什么？）

分离泡产生则推迟了层流边界层的分离，使得翼型升力得到提升

高Tu在特定公交下行程分离泡，并且发生失速现象， 湍流度越高，在翼型表面形成
湍流边界层越厚（抑制层流边界层，所以湍流边界层起主要作用)

低Tu翼型表面边界层较早就发生分离，观察不到分离泡（层流分离？湍流分离？a)
随着湍流度Tu增加，转捩点提前，使层流分离变为湍流分离，因此推迟了分离。


在特大攻角下，湍流度对升力系数影响不大。


**** 粗糙度
粗糙度越大，(提高来流边界层的湍动能，)转捩提前(层流变湍流)[全层流，转捩模型，全湍流模型]
边界层厚度会增加，尾迹也会变宽。

光滑没有分离，反而粗糙度度引入油分离

《翼型薄翼理论》  《黏性翼型空气动力学》
** 工程师就是文档大侠 
 
 [[file:~/.emacs.d/GTD/writing/referencesBak/windEnergy.org]]

                    :PROPERTIES:
                    :CREATED: [2018-12-19 周三 22:36]
                    :END:

                    
看文档知道过程的始末，知道事情的原由。

干了什么，重要吗？ 结果是什么?  

他是什么？ 有什么特点？优缺点? 我需要使用？ 怎么使用？ 使用它需要注意什么？ 有哪些领域可以使用?

行为参数化---lambda编程----跟上java8


你想学什么？ 你想干什么？ 你的wishful thinking是什么?
你的期望是什么?
** 经事 
 
 [[file:k:/IntellijHome/The-Little-Java/README.md::%E6%8E%A5%E5%8F%A3%E9%97%B4%E5%8F%AF%E4%BB%A5%E7%9B%B8%E4%BA%92extends%EF%BC%81%EF%BC%81%E4%B8%80%E6%AC%A1%E7%BB%A7%E6%89%BF%EF%BC%8C%E5%A4%9A%E4%B8%AA%E5%AE%9E%E7%8E%B0%E6%98%AFjava%E7%9A%84%E8%AF%AD%E8%A8%80%E7%89%B9%E6%80%A7%E3%80%82]]

                    :PROPERTIES:
                    :CREATED: [2018-12-23 周日 01:39]
                    :END:

                    
锻炼一个经事的能力，遇事沉着冷静。
善于分析，善于思考


别在人家心里不舒服的时候，扔石头进去，扔进去容易，但是捞出来就不容易了(进去容易，出去难 进气容易，出气难)

学校真的只是打造自己一把锋利的刀刃? 用来解决实际问题！会思考的刀
** 自证思想 
 
 [[file:~/.emacs.d/README.md][file:~/.emacs.d/README.md]]

                    :PROPERTIES:
                    :CREATED: [2018-12-24 周一 00:21]
                    :END:

                    
不严肃的想法

代码有根据需求，可以生成需求代码

其实我们更需要的思想，自生思想，发展思想，诱发思想，
 automate thinking system(AST)--Abstract symbol tree

思想决定着你的思维能动性(思维决定行动)。focus makes you generate thinking recursively.

source of thinking(SOT)应该是一个Y-lambdas(本身就是一个虚拟的系统), 可以根据简单的过程，衍生出一定时间、一定空间(x,y,z)的得到物理的结果。

有技术也得有科学。 你现在技术有一些，但是科学性还得增强
机械(技术)+科学性都得分开

还有比如人文性（历史）等都得学学。出了名的人干出了历史。

(Y F)= (F (Y F))   F其实是closure

Y具有驱动的作用

http://deathking.github.io/2015/03/21/all-about-y-combinator/

http://theschemer.org/t/150

http://www.ece.uc.edu/~franco/C511/html/Scheme/ycomb.html

https://cgi.soic.indiana.edu/~c311/lib/exe/fetch.php?media=cps-notes.scm


http://gauss.ececs.uc.edu/Courses/C626/Lectures/Cryptol/
** 数据的物理机制                                                    :crypt:
-----BEGIN PGP MESSAGE-----

hQEMAw7kGOoigxp9AQgA5jGGeKljUXLQFdL+H3mrid0s+J+os6gTbeV8m5a6pIER
gClV7cswnSySrGgfQYOUxwMeK6JDuN+GandwBLaL8UC8RwTKSejFfQAvqRokqcbq
oiiyWWu8HkZeYKES0bBWN4R3L3dUwA8hceGLoYaT6Cpxke9Lv3XI0aWO6XOeuy2h
tNZG2oz07rJoLNnqVMO+cUJIBWnZLsz3Dmiqv9ODAAA785IIqPhIuaHvdl1cmKh3
GxVMzImf+Iwa9wuldsGiNipB3KUHw9Ryf4gZq0+NehlN3v0PinR0fZpJQ2PSz8nc
t+Q2Dm55JrCk/ZDvSR2M/r0SJHr5B9sBNXpCPX3xbdLrAf2z8hDqIZCkZXDMdu//
MKufRuBHpMQQkXC9TsxRpMA3IxEDZa4i0tlp4cwu0orgFXqWX7tbQXyxHlmzCcgu
OOE5iyk2EgFFU/S5U4NkLhTf5Lrfa57yb15OWES8MEWbURa0U1sxt6TuiFH3yKV2
r4GMVRFAcZ6ReLcvtb3Fvr7k6CrA+SCIvE1nyrz65Mv3YihwLLKuzuqY0kURUp+c
2krkqWE4T9GhP+rEesPoH9GMM1ODK+K0RGL/mpoi7tkv51CgrzcXjJoENTQEwNpX
rS5EdRXTi01qDjiJciI5YsBH7kFe4zrfRAqDNFFE4DC89vezsKDYNCUmYeHG5fn+
eN7kx5V/CAw0Fj+iMblcYJD92BC+heSbmZmkfT42NEh1uNtSGRbKnu41hlOpq6Ff
CgYSzMlPNUqTNMhocgSxtOP9fSRObeIwgw1fbq+Zim9mhE7IIjI2gEif8rfZDTps
cUljXfXP8XhDBL6WCzXdrueO/CMBnJLLcgsdf49E4q7k/HKPfKTMwJKtZ919Z8y1
GjwihaB1svsL6BQZn3Z0OIknOO4hNoQeuJvEx385TAJbUXjTvX2XIRR1NGl4yPHf
Rvvi5YozqbE/A7ulxUuPfqSrVkWtZnpFRpqnqyQQadJiRCOUQsWfk5GcbKC+Ko3o
uc8hsUN6kZjpvH2HSDGed0cPDRPK3UYITWii7Rh+eoH4tWGwiOeUMf2iYvkKSP0F
+xcby5EJ70WqRyUJxAOkb0k5d0E3B4SP0TZ9quOv1NuvbVop7zVfKyXMIVx/Lm4/
fLjI5RS2ahlhQey/dFkjEt8o2eJUskZosSeFSVY3CXs4aGOYTQXJb+hoEk3RQEeg
sLDOUgQbQK2fuhwn58d2wrfQKCLPGcbDfkEso967rmHzp3OR40IBLu5SOapDQQ0g
QUY0JrVo6pL9UcThHxwF6cYK+/ux9IYUKVaNw8KOMGx+22He+pRTcWukHpHsyFKF
SwOYyDbCWh2ABYF3lAX1jTBAiS+IpDTQRKi0aHOBjHDlD2I3oyUieE4TFVY8kTwO
oEz10Fszcyvoxl/28ZPjjqebup+juI3P7pkozMw92HZENMQtDr+OVt+p0d+Youyj
aCI0h7d1JJZeSfCqh/lBZMb9fqLh1Dl5zIVAPMJeeMWKOBVdxYeaRh58qehoFpii
0/Jb68mn+2IRB+XTiLS8FvI0NAeUGH4p+mKowBL67KkcSctE95NcBtYLz4pgT2iB
9dvsryNjIDHTTRFtdf19Bc0qM0ODORSDs/XSQ+Kqarz1sqgd9Z3fRxlk/FvdcAIm
zwmsnP5/9jDHbQIflqeKischYvFg2XvxqVYarEtHoi6VDGPcUuxpAFBMzpcZmIoO
BlyH2NNyhv20RYGhg4DaFpI9wH2DIEOt/dlGBIqdivIbfEhghC2RKBICujBumQIv
wQo+gfJZOt7tvrB3raNYUihgCMtVmopb5GVZwvoiy6OpoVC6QP3YKZD3Sumdlc71
u7wHMgEXDMdmRmb8L/n6OuqhPVETmN7m+DqnVmzXlcNLf7iGTqYi5NHXJnIFI1+x
XQ39ZhHUlO/ef9PuM/BCE2YEl5h/zPAD3JixnBQvqpkVCrtylaBPQttZgfiRmQHZ
CGUUsBmzLXzIsbGqr3b92ILyPBz+wQX3IhnFxjHNymcDJFfXjFnKrVIbznnmCIdL
GYddW8h0M85YGRU79Ewz8D6XTrBuZEEGRjbExEmc+vxHuDojcmXJQoELYPVI5vwt
+RXR+Axg3eaaW00jd0rRPUm0zkbEQxh+JxvmzSTA3Qs4B2oB2/esHYYhukExCdUv
vQTQY/iywDF5lp8OUjuBcTCnI0os80mazedn89yve/DhBxxupw0EIaolW1CiL6rU
u/Rp3wR4JvNXzHe1FsCuUEEqFKXlqZOw9OxY0Qszyi4SV+O65gXwd7+0C8x/b2zx
VPxdbSuNMkAwwh4+NSDCgD69GdIPzF2NJmL/kvbkz7W2sN8QUXixlf+N7lenECEZ
SVY/qDCxgfqgTcz31qRRyTvsCXY6+uQdxFHBOLBmIk3y0dSwkzsBNkVJMLwuQBrg
/eMNyFjbo/qzp0Jg3XakzZU7un0FA3yX2osNUmfJsQBY9glgFF5zr4iNAIf9hLXk
4NvcBnH09hqiwsEXKzziZZ+oDwitKAo8RCDlkKc3TBqYEvJByEgiDCRihcmn5r9r
ODg+lFgJZkKbA0fOpxJQNk4Ptv1ZJvTNdyXEsjL01Z8QyogH3PCTvj1whj6GOlnw
2EQnEU0MobnXmye9C/bIz6sD1uSNm6pQtXjqadNlx4yQr/zpRysSYm0acIsng/ls
xWOF5QZDIKjLPF1wQ5xe7Iyma8ek7W+rd55YQu7X94vDgNAdMYti6hp6ZczoOrrE
FfzWptO+gWhH5T0OlBbAQK5cj2CgV8RUBBGYFITB8kNYkKu+pqUP4evZq8cxSu26
rduGjIIBXQtocTYpCCZpnQ4YtJHjF8OKU4ZBAMYIn8dieOhTev5nWZ7bhuKXnCFj
tEN6y9B0ZkegEaey2I6JYDKIGOFzSr0k8hWM0qpsd3XPuvey2ZFwR/FzyfNIwuDc
7pqBfoAlwOoPOuRT39MoeVZeULWA1vos1X3cD5c3HC8UOOvh9wpkN5DeBfa1eeYJ
W1NmFekhHoFkJ5jzgRy/nCzyV6gvl4ePwxP61MqMzxTXUxTEcl9L2TU9BaDHwzAf
s8w8uvyysGvQBM2ek+yhwVMT9omIjPEk8CrBn1b1XKRKI630hA==
=Ksja
-----END PGP MESSAGE-----
-----BEGIN PGP MESSAGE-----

hQEMAw7kGOoigxp9AQgAr7TDWEzaYOc5LuBJ1n5tuJ+BKnLtLcHDcwMNz7zqCVnJ
8g6RtKY8VKbxsP/RiOaSHf6R8+kK00y+m9tVFuhCUL0sPE1XFn6vXkHeoHNOJSkc
CoQ2OXy5eGfanQWHxqMPq9/VGJGdCU8jtCGhcYpDegArJHODq094Jf4o1dRuGQVT
1A9yyDkcpXmnz1Ay2AQq4hUxpFiTy3u86M5UxJFYI28yiS1EECfrVxlbgJReMN+w
A/RJSOuUy0JO4RJaS+tgqVtyJr6rrqnWCXpwDcFGOnJAcDeMEaO082FosUAFoCVV
suX7pF5Re9VqA7ICYZ45LWrksS3B5f2ERGtIXW3S3tI7AVr3EjnRwpW/SIY3oegw
OaGKGwFG6eMRSyIM4jdkwpypHKUbJOfqMcv6n7lLr26zuTK5xfoFQSlrVuA=
=9AIY
-----END PGP MESSAGE-----
** 纪律的重要性 
 
 [[file:~/.emacs.d/README.md][file:~/.emacs.d/README.md]]

                    :PROPERTIES:
                    :CREATED: [2018-12-31 周一 13:07]
                    :END:

一个人的优秀习惯是由你一个人遵守的良好纪律决定的

纪律规范到你的衣食住行，才能保证在不良局势下，能够止损。
才能保证败军之际能够良好撤军。钢铁般的纪律。

但是论到打战，战斗力远远比纪律更为重要，能够嗷嗷叫的不对和
整齐的不对是不一样的。


闲时要保证良好的纪律，忙时要有嗷嗷叫的架势。
** 工作量的体现 
 
 [[file:~/.emacs.d/README.md][file:~/.emacs.d/README.md]]

                    :PROPERTIES:
                    :CREATED: [2018-12-31 周一 13:14]
                    :END:

                    
一个人的工作量不是靠你计算了多少case，你重复做了多少活

而是看你分析了多少，你做了多少工作得到了一个结果。

》》 答辩，交流等不是累积工作量，而是通过你的分析、总结来体现工作量

为了这个目的(提取规律)，我需要做多少工作
** 有些话说出来叫做故事，说不出来的叫人生 
 
 [[file:~/.emacs.d/README.md::horizontal%20thining(horizontal%20market,%20horizontal%20relationship..%20such%20as%20%E9%99%A4%E4%BA%86%E9%A3%8E%E7%94%B5%E8%BF%98%E6%9C%89%E7%81%AB%E7%94%B5%EF%BC%8C%E6%B0%B4%E7%94%B5%E7%AD%89)]]

                    :PROPERTIES:
                    :CREATED: [2019-01-13 周日 14:40]
                    :END:

                    
达星(周星驰)的故事,其实关系挺好，却一直不说话。

人生得加点广度和神秘感，这样才不会只是别人眼中的故事，或者成为下一代人们书中的故事。
保留一个这时候的质感，不遗传给下一代。

每个时代的质感都是千差万别。奴隶时代，封建时代,新时代。
每个人在不同阶段的质感也不一样。少年，青年，中年，老年，死去的质感。
